/**
 * Copyright 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.waveprotocol.wave.model.id;

import org.waveprotocol.wave.model.util.Preconditions;

/**
 * In the context of a single wave, a wavelet is identified by a tuple of a
 * wave provider domain and a local identifier which is unique within the domain
 * and the wave
 *
 *
 */
public final class WaveletId implements Comparable<WaveletId> {

  private final String domain;
  private final String id;

  /**
   * Creates a WaveletId from a serialized wavelet id.
   * @param waveletIdString a serialized wavelet id
   * @return a WaveletId
   */
  public static WaveletId deserialise(String waveletIdString) {
    return LongIdSerialiser.INSTANCE.deserialiseWaveletId(waveletIdString);
  }

  /**
   * @param domain must not be null. This is assumed to be of a valid canonical domain format.
   * @param id must not be null. This is assumed to be escaped with
   *   SimplePrefixEscaper.DEFAULT_ESCAPER.
   */
  public WaveletId(String domain, String id) {
    if (domain == null || id == null) {
      Preconditions.nullPointer("Cannot create WaveletId with null value in [domain:"
          + domain + "] [id:" + id + "]");
    }
    if (domain.isEmpty() || id.isEmpty()) {
      Preconditions.illegalArgument("Cannot create wave id with empty value in [domain:"
          + domain + "] [id:" + id + "]");
    }

    if (SimplePrefixEscaper.DEFAULT_ESCAPER.hasEscapeCharacters(domain)) {
      Preconditions.illegalArgument(
          "Domain cannot contain characters that requires escaping: " + domain);
    }

    if (!SimplePrefixEscaper.DEFAULT_ESCAPER.isEscapedProperly(IdConstants.TOKEN_SEPARATOR, id)) {
      Preconditions.illegalArgument("Id is not properly escaped: " + id);
    }

    this.domain = domain;
    this.id = id;
  }

  /**
   * @return the domain
   */
  public String getDomain() {
    return domain;
  }

  /**
   * @return the local id
   */
  public String getId() {
    return id;
  }

  /**
   * Serialises this waveletId into a unique string. For any two wavelet ids,
   * waveletId1.serialise().equals(waveletId2.serialise()) iff waveId1.equals(waveId2).
   */
  public String serialise() {
    return LongIdSerialiser.INSTANCE.serialiseWaveletId(this);
  }

  /**
   * Generated by eclipse.
   * {@inheritDoc}
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((domain == null) ? 0 : domain.hashCode());
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  /**
   * Generated by eclipse.
   * {@inheritDoc}
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    WaveletId other = (WaveletId) obj;
    if (!domain.equals(other.domain)) return false;
    if (!id.equals(other.id)) return false;
    return true;
  }

  @Override
  public String toString() {
    return "[WaveletId:" + serialise() + "]";
  }

  @Override
  public int compareTo(WaveletId other) {
    int domainCompare = domain.compareTo(other.domain);
    if (domainCompare == 0) {
      return id.compareTo(other.id);
    } else {
      return domainCompare;
    }
  }
}
