// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.box.common.comms;

import com.google.gwt.core.client.*;

public class ProtocolSubmitResponse extends JavaScriptObject  {


    public static class Builder extends ProtocolSubmitResponse {
      protected Builder() { }
      public final ProtocolSubmitResponse build() {
        return (ProtocolSubmitResponse)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolSubmitResponse instance 
     *
     * @return new ProtocolSubmitResponse instance
     */
    public static native ProtocolSubmitResponse create() /*-{
        return {
          "_protoMessageName": "ProtocolSubmitResponse",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolSubmitResponse> instance 
     *
     * @return new JsArray<ProtocolSubmitResponse> instance
     */
    public static native JsArray<ProtocolSubmitResponse> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolSubmitResponse (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolSubmitResponse
     */
    public static native ProtocolSubmitResponse get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolSubmitResponse> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolSubmitResponse> 
     */
    public static native JsArray<ProtocolSubmitResponse> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolSubmitResponse from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolSubmitResponse 
     */
    public static native ProtocolSubmitResponse parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolSubmitResponse> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolSubmitResponse> 
     */
    public static native JsArray<ProtocolSubmitResponse> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolSubmitResponse the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolSubmitResponse obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + _1);
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_3));

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolSubmitResponse obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected ProtocolSubmitResponse() {}

    // getters and setters

    // operationsApplied

    public final native int getOperationsApplied() /*-{
        return this["1"] || 0;
    }-*/;

    public final native ProtocolSubmitResponse setOperationsApplied(int operationsApplied) /*-{
        this["1"] = operationsApplied;
        return this;
    }-*/;

    public final native void clearOperationsApplied() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasOperationsApplied() /*-{
        return this["1"] != null;
    }-*/;

    // errorMessage

    public final native String getErrorMessage() /*-{
        return this["2"] || "";
    }-*/;

    public final native ProtocolSubmitResponse setErrorMessage(String errorMessage) /*-{
        this["2"] = errorMessage;
        return this;
    }-*/;

    public final native void clearErrorMessage() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasErrorMessage() /*-{
        return this["2"] != null;
    }-*/;

    // hashedVersionAfterApplication

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getHashedVersionAfterApplication() /*-{
        return this["3"];
    }-*/;

    public final native ProtocolSubmitResponse setHashedVersionAfterApplication(org.waveprotocol.wave.federation.ProtocolHashedVersion hashedVersionAfterApplication) /*-{
        this["3"] = hashedVersionAfterApplication;
        return this;
    }-*/;

    public final native void clearHashedVersionAfterApplication() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasHashedVersionAfterApplication() /*-{
        return this["3"] != null;
    }-*/;


}