// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from search.proto

package org.waveprotocol.box.search;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.JsArray;
import com.google.gwt.core.client.JsArrayString;

public class SearchResponse extends JavaScriptObject  {

    public static class Digest extends JavaScriptObject  {


        public static class Builder extends Digest {
          protected Builder() { }
          public final Digest build() {
            return this;
          }
          public static native Builder create() /*-{
            return {
            };
          }-*/;
        }

        public static final Builder newBuilder() {
          return Builder.create();
        }

        /**
         * Creates a new Digest instance
         *
         * @return new Digest instance
         */
        public static native Digest create() /*-{
            return {
              "_protoMessageName": "Digest",
            };
        }-*/;

        /**
         * Creates a new JsArray<Digest> instance
         *
         * @return new JsArray<Digest> instance
         */
        public static native JsArray<Digest> createArray() /*-{
            return [];
        }-*/;

        /**
         * Returns the name of this protocol buffer.
         */
        public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
            return instance._protoMessageName;
        }-*/;

        /**
         * Gets a Digest (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Digest
         */
        public static native Digest get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Gets a JsArray<Digest> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Digest>
         */
        public static native JsArray<Digest> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Parses a Digest from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Digest
         */
        public static native Digest parse(String json) /*-{
            return eval("(" + json + ")");
        }-*/;

        /**
         * Parses a JsArray<Digest> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Digest>
         */
        public static native JsArray<Digest> parseArray(String json) /*-{
            return eval("(" + json + ")");
        }-*/;

        /**
         * Serializes a json object to a json string.
         *
         * @param Digest the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Digest obj) /*-{
            var buf = [];
            var _1 = obj["1"];
            if(_1 != null)
                buf.push("\"1\":\"" + _1 + "\"");
            var _2 = obj["2"];
            if(_2 != null)
                buf.push("\"2\":\"" + _2 + "\"");
            var _3 = obj["3"];
            if(_3 != null)
                buf.push("\"3\":\"" + _3 + "\"");
            var _4 = obj["4"];
            if(_4 != null)
                buf.push("\"4\":" + _4);
            var _5 = obj["5"];
            if(_5 != null)
                buf.push("\"5\":" + _5);
            var _6 = obj["6"];
            if(_6 != null)
                buf.push("\"6\":" + _6);
            var _7 = obj["7"];
            if(_7 != null && _7.length != 0) {
                buf.push("\"7\":[\"" + _7.join("\",\"") + "\"]");
            }
            var _8 = obj["8"];
            if(_8 != null)
                buf.push("\"8\":\"" + _8 + "\"");

            return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
        }-*/;

        public static native boolean isInitialized(Digest obj) /*-{
            return
                obj["2"] != null
                && obj["3"] != null;
        }-*/;

        protected Digest() {}

        // getters and setters

        // title

        public final native String getTitle() /*-{
            return this["1"] || "";
        }-*/;

        public final native Digest setTitle(String title) /*-{
            this["1"] = title;
            return this;
        }-*/;

        public final native void clearTitle() /*-{
            delete this["1"];
        }-*/;

        public final native boolean hasTitle() /*-{
            return this["1"] != null;
        }-*/;

        // snippet

        public final native String getSnippet() /*-{
            return this["2"] || "";
        }-*/;

        public final native Digest setSnippet(String snippet) /*-{
            this["2"] = snippet;
            return this;
        }-*/;

        public final native void clearSnippet() /*-{
            delete this["2"];
        }-*/;

        public final native boolean hasSnippet() /*-{
            return this["2"] != null;
        }-*/;

        // waveId

        public final native String getWaveId() /*-{
            return this["3"] || "";
        }-*/;

        public final native Digest setWaveId(String waveId) /*-{
            this["3"] = waveId;
            return this;
        }-*/;

        public final native void clearWaveId() /*-{
            delete this["3"];
        }-*/;

        public final native boolean hasWaveId() /*-{
            return this["3"] != null;
        }-*/;

        // lastModified

        public final native double getLastModified() /*-{
            return this["4"] || 0;
        }-*/;

        public final native Digest setLastModified(double lastModified) /*-{
            this["4"] = lastModified;
            return this;
        }-*/;

        public final native void clearLastModified() /*-{
            delete this["4"];
        }-*/;

        public final native boolean hasLastModified() /*-{
            return this["4"] != null;
        }-*/;

        // unreadCount

        public final native int getUnreadCount() /*-{
            return this["5"] || 0;
        }-*/;

        public final native Digest setUnreadCount(int unreadCount) /*-{
            this["5"] = unreadCount;
            return this;
        }-*/;

        public final native void clearUnreadCount() /*-{
            delete this["5"];
        }-*/;

        public final native boolean hasUnreadCount() /*-{
            return this["5"] != null;
        }-*/;

        // blipCount

        public final native int getBlipCount() /*-{
            return this["6"] || 0;
        }-*/;

        public final native Digest setBlipCount(int blipCount) /*-{
            this["6"] = blipCount;
            return this;
        }-*/;

        public final native void clearBlipCount() /*-{
            delete this["6"];
        }-*/;

        public final native boolean hasBlipCount() /*-{
            return this["6"] != null;
        }-*/;

        // participants

        public final native JsArrayString getParticipantsArray() /*-{
            return this["7"];
        }-*/;

        public final java.util.List<String> getParticipantsList() {
            JsArrayString array = getParticipantsArray();
            java.util.List<String> list = new java.util.ArrayList<String>();

            if (array == null) {
              return null;
            }
            for (int i=0; i < getParticipantsCount(); i++) {
              list.add(array.get(i));
            }
            return list;
        }

        public final native Digest setParticipantsArray(JsArrayString participants) /*-{
            this["7"] = participants;
            return this;
        }-*/;

        public final native JsArrayString clearParticipantsArray() /*-{
            return (this["7"] = []);
        }-*/;

        public final String getParticipants(int index) {
            JsArrayString array = getParticipantsArray();
            return array == null ? null : array.get(index);
        }

        public final int getParticipantsCount() {
            JsArrayString array = getParticipantsArray();
            return array == null ? 0 : array.length();
        }

        public final void addParticipants(String participants) {
            JsArrayString array = getParticipantsArray();
            if(array == null)
                array = clearParticipantsArray();
            array.push(participants);
        }

        // author

        public final native String getAuthor() /*-{
            return this["8"] || "";
        }-*/;

        public final native Digest setAuthor(String author) /*-{
            this["8"] = author;
            return this;
        }-*/;

        public final native void clearAuthor() /*-{
            delete this["8"];
        }-*/;

        public final native boolean hasAuthor() /*-{
            return this["8"] != null;
        }-*/;


    }

    public static class Builder extends SearchResponse {
      protected Builder() { }
      public final SearchResponse build() {
        return this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }

    /**
     * Creates a new SearchResponse instance
     *
     * @return new SearchResponse instance
     */
    public static native SearchResponse create() /*-{
        return {
          "_protoMessageName": "SearchResponse",
        };
    }-*/;

    /**
     * Creates a new JsArray<SearchResponse> instance
     *
     * @return new JsArray<SearchResponse> instance
     */
    public static native JsArray<SearchResponse> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a SearchResponse (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return SearchResponse
     */
    public static native SearchResponse get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<SearchResponse> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<SearchResponse>
     */
    public static native JsArray<SearchResponse> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a SearchResponse from a json string
     *
     * @param json string to be parsed/evaluated
     * @return SearchResponse
     */
    public static native SearchResponse parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<SearchResponse> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<SearchResponse>
     */
    public static native JsArray<SearchResponse> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Serializes a json object to a json string.
     *
     * @param SearchResponse the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(SearchResponse obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + _2);
        var _3 = obj["3"];
        if(_3 != null && _3.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.search.SearchResponse.Digest::stringify(Lorg/waveprotocol/wave/search/SearchResponse$Digest;);
            for(var i=0,l=_3.length; i<l; i++)
                b.push(fn(_3[i]));
            buf.push("\"3\":[" + b.join(",") + "]");
        }

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;

    public static native boolean isInitialized(SearchResponse obj) /*-{
        return
            obj["1"] != null
            && obj["2"] != null;
    }-*/;

    protected SearchResponse() {}

    // getters and setters

    // query

    public final native String getQuery() /*-{
        return this["1"] || "";
    }-*/;

    public final native SearchResponse setQuery(String query) /*-{
        this["1"] = query;
        return this;
    }-*/;

    public final native void clearQuery() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasQuery() /*-{
        return this["1"] != null;
    }-*/;

    // numResults

    public final native int getNumResults() /*-{
        return this["2"] || 0;
    }-*/;

    public final native SearchResponse setNumResults(int numResults) /*-{
        this["2"] = numResults;
        return this;
    }-*/;

    public final native void clearNumResults() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasNumResults() /*-{
        return this["2"] != null;
    }-*/;

    // digests

    public final native JsArray<Digest> getDigestsArray() /*-{
        return this["3"];
    }-*/;

    public final java.util.List<Digest> getDigestsList() {
        JsArray<Digest> array = getDigestsArray();
        java.util.List<Digest> list = new java.util.ArrayList<Digest>();

        if (array == null) {
          return null;
        }
        for (int i=0; i < getDigestsCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native SearchResponse setDigestsArray(JsArray<Digest> digests) /*-{
        this["3"] = digests;
        return this;
    }-*/;

    public final native JsArray<Digest> clearDigestsArray() /*-{
        return (this["3"] = []);
    }-*/;

    public final Digest getDigests(int index) {
        JsArray<Digest> array = getDigestsArray();
        return array == null ? null : array.get(index);
    }

    public final int getDigestsCount() {
        JsArray<Digest> array = getDigestsArray();
        return array == null ? 0 : array.length();
    }

    public final void addDigests(Digest digests) {
        JsArray<Digest> array = getDigestsArray();
        if(array == null)
            array = clearDigestsArray();
        array.push(digests);
    }


}