// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from search.proto

package org.waveprotocol.box.search;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.JsArray;

public class SearchRequest extends JavaScriptObject  {


    public static class Builder extends SearchRequest {
      protected Builder() { }
      public final SearchRequest build() {
        return this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }

    /**
     * Creates a new SearchRequest instance
     *
     * @return new SearchRequest instance
     */
    public static native SearchRequest create() /*-{
        return {
          "_protoMessageName": "SearchRequest",
        };
    }-*/;

    /**
     * Creates a new JsArray<SearchRequest> instance
     *
     * @return new JsArray<SearchRequest> instance
     */
    public static native JsArray<SearchRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a SearchRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return SearchRequest
     */
    public static native SearchRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<SearchRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<SearchRequest>
     */
    public static native JsArray<SearchRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a SearchRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return SearchRequest
     */
    public static native SearchRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<SearchRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<SearchRequest>
     */
    public static native JsArray<SearchRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Serializes a json object to a json string.
     *
     * @param SearchRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(SearchRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + _2);
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + _3);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;

    public static native boolean isInitialized(SearchRequest obj) /*-{
        return
            obj["1"] != null
            && obj["2"] != null
            && obj["3"] != null;
    }-*/;

    protected SearchRequest() {}

    // getters and setters

    // query

    public final native String getQuery() /*-{
        return this["1"] || "";
    }-*/;

    public final native SearchRequest setQuery(String query) /*-{
        this["1"] = query;
        return this;
    }-*/;

    public final native void clearQuery() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasQuery() /*-{
        return this["1"] != null;
    }-*/;

    // index

    public final native int getIndex() /*-{
        return this["2"] || 0;
    }-*/;

    public final native SearchRequest setIndex(int index) /*-{
        this["2"] = index;
        return this;
    }-*/;

    public final native void clearIndex() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasIndex() /*-{
        return this["2"] != null;
    }-*/;

    // numResults

    public final native int getNumResults() /*-{
        return this["3"] || 0;
    }-*/;

    public final native SearchRequest setNumResults(int numResults) /*-{
        this["3"] = numResults;
        return this;
    }-*/;

    public final native void clearNumResults() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasNumResults() /*-{
        return this["3"] != null;
    }-*/;


}