// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.box.server.waveserver;

import com.google.gwt.core.client.*;

public class ProtocolOpenRequest extends JavaScriptObject  {


    public static class Builder extends ProtocolOpenRequest {
      protected Builder() { }
      public final ProtocolOpenRequest build() {
        return (ProtocolOpenRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolOpenRequest instance 
     *
     * @return new ProtocolOpenRequest instance
     */
    public static native ProtocolOpenRequest create() /*-{
        return {
          "_protoMessageName": "ProtocolOpenRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolOpenRequest> instance 
     *
     * @return new JsArray<ProtocolOpenRequest> instance
     */
    public static native JsArray<ProtocolOpenRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolOpenRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolOpenRequest
     */
    public static native ProtocolOpenRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolOpenRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolOpenRequest> 
     */
    public static native JsArray<ProtocolOpenRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolOpenRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolOpenRequest 
     */
    public static native ProtocolOpenRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolOpenRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolOpenRequest> 
     */
    public static native JsArray<ProtocolOpenRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolOpenRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolOpenRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null && _3.length != 0) {
            buf.push("\"3\":[\"" + _3.join("\",\"") + "\"]");
        }
        var _4 = obj["4"];
        if(_4 != null && _4.length != 0) {
            var b = [], fn = @org.waveprotocol.box.server.waveserver.WaveletVersion::stringify(Lorg/waveprotocol/box/server/waveserver/WaveletVersion;);
            for(var i=0,l=_4.length; i<l; i++)
                b.push(fn(_4[i]));
            buf.push("\"4\":[" + b.join(",") + "]");
        }

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolOpenRequest obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected ProtocolOpenRequest() {}

    // getters and setters

    // participantId

    public final native String getParticipantId() /*-{
        return this["1"] || "";
    }-*/;

    public final native ProtocolOpenRequest setParticipantId(String participantId) /*-{
        this["1"] = participantId;
        return this;
    }-*/;

    public final native void clearParticipantId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasParticipantId() /*-{
        return this["1"] != null;
    }-*/;

    // waveId

    public final native String getWaveId() /*-{
        return this["2"] || "";
    }-*/;

    public final native ProtocolOpenRequest setWaveId(String waveId) /*-{
        this["2"] = waveId;
        return this;
    }-*/;

    public final native void clearWaveId() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasWaveId() /*-{
        return this["2"] != null;
    }-*/;

    // waveletIdPrefix

    public final native JsArrayString getWaveletIdPrefixArray() /*-{
        return this["3"];
    }-*/;

    public final java.util.List<String> getWaveletIdPrefixList() {
        JsArrayString array = getWaveletIdPrefixArray();
        java.util.List<String> list = new java.util.ArrayList<String>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getWaveletIdPrefixCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolOpenRequest setWaveletIdPrefixArray(JsArrayString waveletIdPrefix) /*-{
        this["3"] = waveletIdPrefix;
        return this;
    }-*/;

    public final native JsArrayString clearWaveletIdPrefixArray() /*-{
        return (this["3"] = []);
    }-*/;

    public final String getWaveletIdPrefix(int index) {
        JsArrayString array = getWaveletIdPrefixArray();
        return array == null ? null : array.get(index);
    }

    public final int getWaveletIdPrefixCount() {
        JsArrayString array = getWaveletIdPrefixArray();
        return array == null ? 0 : array.length();
    }

    public final void addWaveletIdPrefix(String waveletIdPrefix) {
        JsArrayString array = getWaveletIdPrefixArray();
        if(array == null)
            array = clearWaveletIdPrefixArray();
        array.push(waveletIdPrefix);
    }

    // knownWavelet

    public final native JsArray<WaveletVersion> getKnownWaveletArray() /*-{
        return this["4"];
    }-*/;

    public final java.util.List<WaveletVersion> getKnownWaveletList() {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        java.util.List<WaveletVersion> list = new java.util.ArrayList<WaveletVersion>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getKnownWaveletCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolOpenRequest setKnownWaveletArray(JsArray<WaveletVersion> knownWavelet) /*-{
        this["4"] = knownWavelet;
        return this;
    }-*/;

    public final native JsArray<WaveletVersion> clearKnownWaveletArray() /*-{
        return (this["4"] = []);
    }-*/;

    public final WaveletVersion getKnownWavelet(int index) {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        return array == null ? null : array.get(index);
    }

    public final int getKnownWaveletCount() {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        return array == null ? 0 : array.length();
    }

    public final void addKnownWavelet(WaveletVersion knownWavelet) {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        if(array == null)
            array = clearKnownWaveletArray();
        array.push(knownWavelet);
    }


}