// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolWaveletDelta extends JavaScriptObject  {


    public static class Builder extends ProtocolWaveletDelta {
      protected Builder() { }
      public final ProtocolWaveletDelta build() {
        return (ProtocolWaveletDelta)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolWaveletDelta instance 
     *
     * @return new ProtocolWaveletDelta instance
     */
    public static native ProtocolWaveletDelta create() /*-{
        return {
          "_protoMessageName": "ProtocolWaveletDelta",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolWaveletDelta> instance 
     *
     * @return new JsArray<ProtocolWaveletDelta> instance
     */
    public static native JsArray<ProtocolWaveletDelta> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolWaveletDelta (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolWaveletDelta
     */
    public static native ProtocolWaveletDelta get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolWaveletDelta> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolWaveletDelta> 
     */
    public static native JsArray<ProtocolWaveletDelta> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolWaveletDelta from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolWaveletDelta 
     */
    public static native ProtocolWaveletDelta parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolWaveletDelta> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolWaveletDelta> 
     */
    public static native JsArray<ProtocolWaveletDelta> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolWaveletDelta the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolWaveletDelta obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_1));
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null && _3.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.federation.ProtocolWaveletOperation::stringify(Lorg/waveprotocol/wave/federation/ProtocolWaveletOperation;);
            for(var i=0,l=_3.length; i<l; i++)
                b.push(fn(_3[i]));
            buf.push("\"3\":[" + b.join(",") + "]");
        }
        var _4 = obj["4"];
        if(_4 != null && _4.length != 0) {
            buf.push("\"4\":[\"" + _4.join("\",\"") + "\"]");
        }

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolWaveletDelta obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected ProtocolWaveletDelta() {}

    // getters and setters

    // hashedVersion

    public final native ProtocolHashedVersion getHashedVersion() /*-{
        return this["1"];
    }-*/;

    public final native ProtocolWaveletDelta setHashedVersion(ProtocolHashedVersion hashedVersion) /*-{
        this["1"] = hashedVersion;
        return this;
    }-*/;

    public final native void clearHashedVersion() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasHashedVersion() /*-{
        return this["1"] != null;
    }-*/;

    // author

    public final native String getAuthor() /*-{
        return this["2"] || "";
    }-*/;

    public final native ProtocolWaveletDelta setAuthor(String author) /*-{
        this["2"] = author;
        return this;
    }-*/;

    public final native void clearAuthor() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasAuthor() /*-{
        return this["2"] != null;
    }-*/;

    // operation

    public final native JsArray<ProtocolWaveletOperation> getOperationArray() /*-{
        return this["3"];
    }-*/;

    public final java.util.List<ProtocolWaveletOperation> getOperationList() {
        JsArray<ProtocolWaveletOperation> array = getOperationArray();
        java.util.List<ProtocolWaveletOperation> list = new java.util.ArrayList<ProtocolWaveletOperation>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getOperationCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolWaveletDelta setOperationArray(JsArray<ProtocolWaveletOperation> operation) /*-{
        this["3"] = operation;
        return this;
    }-*/;

    public final native JsArray<ProtocolWaveletOperation> clearOperationArray() /*-{
        return (this["3"] = []);
    }-*/;

    public final ProtocolWaveletOperation getOperation(int index) {
        JsArray<ProtocolWaveletOperation> array = getOperationArray();
        return array == null ? null : array.get(index);
    }

    public final int getOperationCount() {
        JsArray<ProtocolWaveletOperation> array = getOperationArray();
        return array == null ? 0 : array.length();
    }

    public final void addOperation(ProtocolWaveletOperation operation) {
        JsArray<ProtocolWaveletOperation> array = getOperationArray();
        if(array == null)
            array = clearOperationArray();
        array.push(operation);
    }

    // addressPath

    public final native JsArrayString getAddressPathArray() /*-{
        return this["4"];
    }-*/;

    public final java.util.List<String> getAddressPathList() {
        JsArrayString array = getAddressPathArray();
        java.util.List<String> list = new java.util.ArrayList<String>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getAddressPathCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolWaveletDelta setAddressPathArray(JsArrayString addressPath) /*-{
        this["4"] = addressPath;
        return this;
    }-*/;

    public final native JsArrayString clearAddressPathArray() /*-{
        return (this["4"] = []);
    }-*/;

    public final String getAddressPath(int index) {
        JsArrayString array = getAddressPathArray();
        return array == null ? null : array.get(index);
    }

    public final int getAddressPathCount() {
        JsArrayString array = getAddressPathArray();
        return array == null ? 0 : array.length();
    }

    public final void addAddressPath(String addressPath) {
        JsArrayString array = getAddressPathArray();
        if(array == null)
            array = clearAddressPathArray();
        array.push(addressPath);
    }


}