// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolWaveletOperation extends JavaScriptObject  {

    public static class MutateDocument extends JavaScriptObject  {


        public static class Builder extends MutateDocument {
          protected Builder() { }
          public final MutateDocument build() {
            return (MutateDocument)this;
          }
          public static native Builder create() /*-{
            return {
            };
          }-*/;
        }

        public static final Builder newBuilder() {
          return Builder.create();
        }
        
        /**
         * Creates a new MutateDocument instance 
         *
         * @return new MutateDocument instance
         */
        public static native MutateDocument create() /*-{
            return {
              "_protoMessageName": "MutateDocument",              
            };
        }-*/;

        /**
         * Creates a new JsArray<MutateDocument> instance 
         *
         * @return new JsArray<MutateDocument> instance
         */
        public static native JsArray<MutateDocument> createArray() /*-{
            return [];
        }-*/;

        /**
         * Returns the name of this protocol buffer.
         */
        public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
            return instance._protoMessageName;
        }-*/;

        /**
         * Gets a MutateDocument (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return MutateDocument
         */
        public static native MutateDocument get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Gets a JsArray<MutateDocument> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<MutateDocument> 
         */
        public static native JsArray<MutateDocument> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Parses a MutateDocument from a json string
         *
         * @param json string to be parsed/evaluated
         * @return MutateDocument 
         */
        public static native MutateDocument parse(String json) /*-{
            return eval("(" + json + ")");
        }-*/;

        /**
         * Parses a JsArray<MutateDocument> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<MutateDocument> 
         */
        public static native JsArray<MutateDocument> parseArray(String json) /*-{
            return eval("(" + json + ")");
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param MutateDocument the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(MutateDocument obj) /*-{
            var buf = [];
            var _1 = obj["1"];
            if(_1 != null)
                buf.push("\"1\":\"" + _1 + "\"");
            var _2 = obj["2"];
            if(_2 != null)
                buf.push("\"2\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation;)(_2));

            return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
        }-*/;
        
        public static native boolean isInitialized(MutateDocument obj) /*-{
            return 
                obj["1"] != null 
                && obj["2"] != null;
        }-*/;

        protected MutateDocument() {}

        // getters and setters

        // documentId

        public final native String getDocumentId() /*-{
            return this["1"] || "";
        }-*/;

        public final native MutateDocument setDocumentId(String documentId) /*-{
            this["1"] = documentId;
            return this;
        }-*/;

        public final native void clearDocumentId() /*-{
            delete this["1"];
        }-*/;

        public final native boolean hasDocumentId() /*-{
            return this["1"] != null;
        }-*/;

        // documentOperation

        public final native ProtocolDocumentOperation getDocumentOperation() /*-{
            return this["2"];
        }-*/;

        public final native MutateDocument setDocumentOperation(ProtocolDocumentOperation documentOperation) /*-{
            this["2"] = documentOperation;
            return this;
        }-*/;

        public final native void clearDocumentOperation() /*-{
            delete this["2"];
        }-*/;

        public final native boolean hasDocumentOperation() /*-{
            return this["2"] != null;
        }-*/;


    }

    public static class Builder extends ProtocolWaveletOperation {
      protected Builder() { }
      public final ProtocolWaveletOperation build() {
        return (ProtocolWaveletOperation)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolWaveletOperation instance 
     *
     * @return new ProtocolWaveletOperation instance
     */
    public static native ProtocolWaveletOperation create() /*-{
        return {
          "_protoMessageName": "ProtocolWaveletOperation",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolWaveletOperation> instance 
     *
     * @return new JsArray<ProtocolWaveletOperation> instance
     */
    public static native JsArray<ProtocolWaveletOperation> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolWaveletOperation (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolWaveletOperation
     */
    public static native ProtocolWaveletOperation get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolWaveletOperation> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolWaveletOperation> 
     */
    public static native JsArray<ProtocolWaveletOperation> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolWaveletOperation from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolWaveletOperation 
     */
    public static native ProtocolWaveletOperation parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolWaveletOperation> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolWaveletOperation> 
     */
    public static native JsArray<ProtocolWaveletOperation> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolWaveletOperation the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolWaveletOperation obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolWaveletOperation.MutateDocument::stringify(Lorg/waveprotocol/wave/federation/ProtocolWaveletOperation$MutateDocument;)(_3));
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":" + _4);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolWaveletOperation obj) /*-{
        return true;
    }-*/;

    protected ProtocolWaveletOperation() {}

    // getters and setters

    // addParticipant

    public final native String getAddParticipant() /*-{
        return this["1"] || "";
    }-*/;

    public final native ProtocolWaveletOperation setAddParticipant(String addParticipant) /*-{
        this["1"] = addParticipant;
        return this;
    }-*/;

    public final native void clearAddParticipant() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasAddParticipant() /*-{
        return this["1"] != null;
    }-*/;

    // removeParticipant

    public final native String getRemoveParticipant() /*-{
        return this["2"] || "";
    }-*/;

    public final native ProtocolWaveletOperation setRemoveParticipant(String removeParticipant) /*-{
        this["2"] = removeParticipant;
        return this;
    }-*/;

    public final native void clearRemoveParticipant() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasRemoveParticipant() /*-{
        return this["2"] != null;
    }-*/;

    // mutateDocument

    public final native MutateDocument getMutateDocument() /*-{
        return this["3"];
    }-*/;

    public final native ProtocolWaveletOperation setMutateDocument(MutateDocument mutateDocument) /*-{
        this["3"] = mutateDocument;
        return this;
    }-*/;

    public final native void clearMutateDocument() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasMutateDocument() /*-{
        return this["3"] != null;
    }-*/;

    // noOp

    public final native boolean getNoOp() /*-{
        return this["4"] || false;
    }-*/;

    public final native ProtocolWaveletOperation setNoOp(boolean noOp) /*-{
        this["4"] = noOp;
        return this;
    }-*/;

    public final native void clearNoOp() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasNoOp() /*-{
        return this["4"] != null;
    }-*/;


}