// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolSignature extends JavaScriptObject  {

    public static class SignatureAlgorithm extends JavaScriptObject {
            
        public static final SignatureAlgorithm SHA1_RSA = create(1);
        
        private static native SignatureAlgorithm create(int number) /*-{
            return number;
        }-*/;
        
        protected SignatureAlgorithm() {}

        public final native int getNumber() /*-{
            return this;
        }-*/;
        
    }


    public static class Builder extends ProtocolSignature {
      protected Builder() { }
      public final ProtocolSignature build() {
        return (ProtocolSignature)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolSignature instance 
     *
     * @return new ProtocolSignature instance
     */
    public static native ProtocolSignature create() /*-{
        return {
          "_protoMessageName": "ProtocolSignature",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolSignature> instance 
     *
     * @return new JsArray<ProtocolSignature> instance
     */
    public static native JsArray<ProtocolSignature> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolSignature (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolSignature
     */
    public static native ProtocolSignature get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolSignature> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolSignature> 
     */
    public static native JsArray<ProtocolSignature> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolSignature from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolSignature 
     */
    public static native ProtocolSignature parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolSignature> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolSignature> 
     */
    public static native JsArray<ProtocolSignature> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolSignature the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolSignature obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + _3);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolSignature obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null 
            && obj["3"] != null;
    }-*/;

    protected ProtocolSignature() {}

    // getters and setters

    // signatureBytes

    public final native String getSignatureBytes() /*-{
        return this["1"];
    }-*/;

    public final native ProtocolSignature setSignatureBytes(String signatureBytes) /*-{
        this["1"] = signatureBytes;
        return this;
    }-*/;

    public final native void clearSignatureBytes() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasSignatureBytes() /*-{
        return this["1"] != null;
    }-*/;

    // signerId

    public final native String getSignerId() /*-{
        return this["2"];
    }-*/;

    public final native ProtocolSignature setSignerId(String signerId) /*-{
        this["2"] = signerId;
        return this;
    }-*/;

    public final native void clearSignerId() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasSignerId() /*-{
        return this["2"] != null;
    }-*/;

    // signatureAlgorithm

    public final native SignatureAlgorithm getSignatureAlgorithm() /*-{
        var v = this["3"];
        return v == null ? 1 : v;
    }-*/;

    public final native ProtocolSignature setSignatureAlgorithm(SignatureAlgorithm signatureAlgorithm) /*-{
        this["3"] = signatureAlgorithm;
        return this;
    }-*/;

    public final native void clearSignatureAlgorithm() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasSignatureAlgorithm() /*-{
        return this["3"] != null;
    }-*/;


}