// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolAppliedWaveletDelta extends JavaScriptObject  {


    public static class Builder extends ProtocolAppliedWaveletDelta {
      protected Builder() { }
      public final ProtocolAppliedWaveletDelta build() {
        return (ProtocolAppliedWaveletDelta)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolAppliedWaveletDelta instance 
     *
     * @return new ProtocolAppliedWaveletDelta instance
     */
    public static native ProtocolAppliedWaveletDelta create() /*-{
        return {
          "_protoMessageName": "ProtocolAppliedWaveletDelta",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolAppliedWaveletDelta> instance 
     *
     * @return new JsArray<ProtocolAppliedWaveletDelta> instance
     */
    public static native JsArray<ProtocolAppliedWaveletDelta> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolAppliedWaveletDelta (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolAppliedWaveletDelta
     */
    public static native ProtocolAppliedWaveletDelta get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolAppliedWaveletDelta> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolAppliedWaveletDelta> 
     */
    public static native JsArray<ProtocolAppliedWaveletDelta> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolAppliedWaveletDelta from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolAppliedWaveletDelta 
     */
    public static native ProtocolAppliedWaveletDelta parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolAppliedWaveletDelta> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolAppliedWaveletDelta> 
     */
    public static native JsArray<ProtocolAppliedWaveletDelta> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolAppliedWaveletDelta the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolAppliedWaveletDelta obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + @org.waveprotocol.wave.federation.ProtocolSignedDelta::stringify(Lorg/waveprotocol/wave/federation/ProtocolSignedDelta;)(_1));
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_2));
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + _3);
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":" + _4);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolAppliedWaveletDelta obj) /*-{
        return 
            obj["1"] != null 
            && obj["3"] != null 
            && obj["4"] != null;
    }-*/;

    protected ProtocolAppliedWaveletDelta() {}

    // getters and setters

    // signedOriginalDelta

    public final native ProtocolSignedDelta getSignedOriginalDelta() /*-{
        return this["1"];
    }-*/;

    public final native ProtocolAppliedWaveletDelta setSignedOriginalDelta(ProtocolSignedDelta signedOriginalDelta) /*-{
        this["1"] = signedOriginalDelta;
        return this;
    }-*/;

    public final native void clearSignedOriginalDelta() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasSignedOriginalDelta() /*-{
        return this["1"] != null;
    }-*/;

    // hashedVersionAppliedAt

    public final native ProtocolHashedVersion getHashedVersionAppliedAt() /*-{
        return this["2"];
    }-*/;

    public final native ProtocolAppliedWaveletDelta setHashedVersionAppliedAt(ProtocolHashedVersion hashedVersionAppliedAt) /*-{
        this["2"] = hashedVersionAppliedAt;
        return this;
    }-*/;

    public final native void clearHashedVersionAppliedAt() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasHashedVersionAppliedAt() /*-{
        return this["2"] != null;
    }-*/;

    // operationsApplied

    public final native int getOperationsApplied() /*-{
        return this["3"] || 0;
    }-*/;

    public final native ProtocolAppliedWaveletDelta setOperationsApplied(int operationsApplied) /*-{
        this["3"] = operationsApplied;
        return this;
    }-*/;

    public final native void clearOperationsApplied() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasOperationsApplied() /*-{
        return this["3"] != null;
    }-*/;

    // applicationTimestamp

    public final native double getApplicationTimestamp() /*-{
        return this["4"] || 0;
    }-*/;

    public final native ProtocolAppliedWaveletDelta setApplicationTimestamp(double applicationTimestamp) /*-{
        this["4"] = applicationTimestamp;
        return this;
    }-*/;

    public final native void clearApplicationTimestamp() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasApplicationTimestamp() /*-{
        return this["4"] != null;
    }-*/;


}