// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolHashedVersion extends JavaScriptObject  {


    public static class Builder extends ProtocolHashedVersion {
      protected Builder() { }
      public final ProtocolHashedVersion build() {
        return (ProtocolHashedVersion)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolHashedVersion instance 
     *
     * @return new ProtocolHashedVersion instance
     */
    public static native ProtocolHashedVersion create() /*-{
        return {
          "_protoMessageName": "ProtocolHashedVersion",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolHashedVersion> instance 
     *
     * @return new JsArray<ProtocolHashedVersion> instance
     */
    public static native JsArray<ProtocolHashedVersion> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolHashedVersion (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolHashedVersion
     */
    public static native ProtocolHashedVersion get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolHashedVersion> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolHashedVersion> 
     */
    public static native JsArray<ProtocolHashedVersion> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolHashedVersion from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolHashedVersion 
     */
    public static native ProtocolHashedVersion parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolHashedVersion> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolHashedVersion> 
     */
    public static native JsArray<ProtocolHashedVersion> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolHashedVersion the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolHashedVersion obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + _1);
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolHashedVersion obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected ProtocolHashedVersion() {}

    // getters and setters

    // version

    public final native double getVersion() /*-{
        return this["1"] || 0;
    }-*/;

    public final native ProtocolHashedVersion setVersion(double version) /*-{
        this["1"] = version;
        return this;
    }-*/;

    public final native void clearVersion() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasVersion() /*-{
        return this["1"] != null;
    }-*/;

    // historyHash

    public final native String getHistoryHash() /*-{
        return this["2"];
    }-*/;

    public final native ProtocolHashedVersion setHistoryHash(String historyHash) /*-{
        this["2"] = historyHash;
        return this;
    }-*/;

    public final native void clearHistoryHash() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasHistoryHash() /*-{
        return this["2"] != null;
    }-*/;


}