// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from federation.protodevel

package org.waveprotocol.wave.federation;

import com.google.gwt.core.client.*;

public class ProtocolDocumentOperation extends JavaScriptObject  {

    public static class Component extends JavaScriptObject  {

        public static class KeyValuePair extends JavaScriptObject  {


            public static class Builder extends KeyValuePair {
              protected Builder() { }
              public final KeyValuePair build() {
                return (KeyValuePair)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new KeyValuePair instance 
             *
             * @return new KeyValuePair instance
             */
            public static native KeyValuePair create() /*-{
                return {
                  "_protoMessageName": "KeyValuePair",              
                };
            }-*/;

            /**
             * Creates a new JsArray<KeyValuePair> instance 
             *
             * @return new JsArray<KeyValuePair> instance
             */
            public static native JsArray<KeyValuePair> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a KeyValuePair (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return KeyValuePair
             */
            public static native KeyValuePair get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<KeyValuePair> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<KeyValuePair> 
             */
            public static native JsArray<KeyValuePair> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a KeyValuePair from a json string
             *
             * @param json string to be parsed/evaluated
             * @return KeyValuePair 
             */
            public static native KeyValuePair parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<KeyValuePair> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<KeyValuePair> 
             */
            public static native JsArray<KeyValuePair> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param KeyValuePair the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(KeyValuePair obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":\"" + _1 + "\"");
                var _2 = obj["2"];
                if(_2 != null)
                    buf.push("\"2\":\"" + _2 + "\"");

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(KeyValuePair obj) /*-{
                return 
                    obj["1"] != null 
                    && obj["2"] != null;
            }-*/;

            protected KeyValuePair() {}

            // getters and setters

            // key

            public final native String getKey() /*-{
                return this["1"] || "";
            }-*/;

            public final native KeyValuePair setKey(String key) /*-{
                this["1"] = key;
                return this;
            }-*/;

            public final native void clearKey() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasKey() /*-{
                return this["1"] != null;
            }-*/;

            // value

            public final native String getValue() /*-{
                return this["2"] || "";
            }-*/;

            public final native KeyValuePair setValue(String value) /*-{
                this["2"] = value;
                return this;
            }-*/;

            public final native void clearValue() /*-{
                delete this["2"];
            }-*/;

            public final native boolean hasValue() /*-{
                return this["2"] != null;
            }-*/;


        }public static class KeyValueUpdate extends JavaScriptObject  {


            public static class Builder extends KeyValueUpdate {
              protected Builder() { }
              public final KeyValueUpdate build() {
                return (KeyValueUpdate)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new KeyValueUpdate instance 
             *
             * @return new KeyValueUpdate instance
             */
            public static native KeyValueUpdate create() /*-{
                return {
                  "_protoMessageName": "KeyValueUpdate",              
                };
            }-*/;

            /**
             * Creates a new JsArray<KeyValueUpdate> instance 
             *
             * @return new JsArray<KeyValueUpdate> instance
             */
            public static native JsArray<KeyValueUpdate> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a KeyValueUpdate (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return KeyValueUpdate
             */
            public static native KeyValueUpdate get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<KeyValueUpdate> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<KeyValueUpdate> 
             */
            public static native JsArray<KeyValueUpdate> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a KeyValueUpdate from a json string
             *
             * @param json string to be parsed/evaluated
             * @return KeyValueUpdate 
             */
            public static native KeyValueUpdate parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<KeyValueUpdate> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<KeyValueUpdate> 
             */
            public static native JsArray<KeyValueUpdate> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param KeyValueUpdate the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(KeyValueUpdate obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":\"" + _1 + "\"");
                var _2 = obj["2"];
                if(_2 != null)
                    buf.push("\"2\":\"" + _2 + "\"");
                var _3 = obj["3"];
                if(_3 != null)
                    buf.push("\"3\":\"" + _3 + "\"");

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(KeyValueUpdate obj) /*-{
                return 
                    obj["1"] != null;
            }-*/;

            protected KeyValueUpdate() {}

            // getters and setters

            // key

            public final native String getKey() /*-{
                return this["1"] || "";
            }-*/;

            public final native KeyValueUpdate setKey(String key) /*-{
                this["1"] = key;
                return this;
            }-*/;

            public final native void clearKey() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasKey() /*-{
                return this["1"] != null;
            }-*/;

            // oldValue

            public final native String getOldValue() /*-{
                return this["2"] || "";
            }-*/;

            public final native KeyValueUpdate setOldValue(String oldValue) /*-{
                this["2"] = oldValue;
                return this;
            }-*/;

            public final native void clearOldValue() /*-{
                delete this["2"];
            }-*/;

            public final native boolean hasOldValue() /*-{
                return this["2"] != null;
            }-*/;

            // newValue

            public final native String getNewValue() /*-{
                return this["3"] || "";
            }-*/;

            public final native KeyValueUpdate setNewValue(String newValue) /*-{
                this["3"] = newValue;
                return this;
            }-*/;

            public final native void clearNewValue() /*-{
                delete this["3"];
            }-*/;

            public final native boolean hasNewValue() /*-{
                return this["3"] != null;
            }-*/;


        }public static class ElementStart extends JavaScriptObject  {


            public static class Builder extends ElementStart {
              protected Builder() { }
              public final ElementStart build() {
                return (ElementStart)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new ElementStart instance 
             *
             * @return new ElementStart instance
             */
            public static native ElementStart create() /*-{
                return {
                  "_protoMessageName": "ElementStart",              
                };
            }-*/;

            /**
             * Creates a new JsArray<ElementStart> instance 
             *
             * @return new JsArray<ElementStart> instance
             */
            public static native JsArray<ElementStart> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a ElementStart (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return ElementStart
             */
            public static native ElementStart get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<ElementStart> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<ElementStart> 
             */
            public static native JsArray<ElementStart> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a ElementStart from a json string
             *
             * @param json string to be parsed/evaluated
             * @return ElementStart 
             */
            public static native ElementStart parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<ElementStart> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<ElementStart> 
             */
            public static native JsArray<ElementStart> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param ElementStart the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(ElementStart obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":\"" + _1 + "\"");
                var _2 = obj["2"];
                if(_2 != null && _2.length != 0) {
                    var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.KeyValuePair::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$KeyValuePair;);
                    for(var i=0,l=_2.length; i<l; i++)
                        b.push(fn(_2[i]));
                    buf.push("\"2\":[" + b.join(",") + "]");
                }

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(ElementStart obj) /*-{
                return 
                    obj["1"] != null;
            }-*/;

            protected ElementStart() {}

            // getters and setters

            // type

            public final native String getType() /*-{
                return this["1"] || "";
            }-*/;

            public final native ElementStart setType(String type) /*-{
                this["1"] = type;
                return this;
            }-*/;

            public final native void clearType() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasType() /*-{
                return this["1"] != null;
            }-*/;

            // attribute

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> getAttributeArray() /*-{
                return this["2"];
            }-*/;

            public final java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> getAttributeList() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getAttributeArray();
                java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> list = new java.util.ArrayList<ProtocolDocumentOperation.Component.KeyValuePair>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getAttributeCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native ElementStart setAttributeArray(JsArray<ProtocolDocumentOperation.Component.KeyValuePair> attribute) /*-{
                this["2"] = attribute;
                return this;
            }-*/;

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> clearAttributeArray() /*-{
                return (this["2"] = []);
            }-*/;

            public final ProtocolDocumentOperation.Component.KeyValuePair getAttribute(int index) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getAttributeArray();
                return array == null ? null : array.get(index);
            }

            public final int getAttributeCount() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getAttributeArray();
                return array == null ? 0 : array.length();
            }

            public final void addAttribute(ProtocolDocumentOperation.Component.KeyValuePair attribute) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getAttributeArray();
                if(array == null)
                    array = clearAttributeArray();
                array.push(attribute);
            }


        }public static class ReplaceAttributes extends JavaScriptObject  {


            public static class Builder extends ReplaceAttributes {
              protected Builder() { }
              public final ReplaceAttributes build() {
                return (ReplaceAttributes)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new ReplaceAttributes instance 
             *
             * @return new ReplaceAttributes instance
             */
            public static native ReplaceAttributes create() /*-{
                return {
                  "_protoMessageName": "ReplaceAttributes",              
                };
            }-*/;

            /**
             * Creates a new JsArray<ReplaceAttributes> instance 
             *
             * @return new JsArray<ReplaceAttributes> instance
             */
            public static native JsArray<ReplaceAttributes> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a ReplaceAttributes (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return ReplaceAttributes
             */
            public static native ReplaceAttributes get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<ReplaceAttributes> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<ReplaceAttributes> 
             */
            public static native JsArray<ReplaceAttributes> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a ReplaceAttributes from a json string
             *
             * @param json string to be parsed/evaluated
             * @return ReplaceAttributes 
             */
            public static native ReplaceAttributes parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<ReplaceAttributes> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<ReplaceAttributes> 
             */
            public static native JsArray<ReplaceAttributes> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param ReplaceAttributes the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(ReplaceAttributes obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":" + _1);
                var _2 = obj["2"];
                if(_2 != null && _2.length != 0) {
                    var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.KeyValuePair::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$KeyValuePair;);
                    for(var i=0,l=_2.length; i<l; i++)
                        b.push(fn(_2[i]));
                    buf.push("\"2\":[" + b.join(",") + "]");
                }
                var _3 = obj["3"];
                if(_3 != null && _3.length != 0) {
                    var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.KeyValuePair::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$KeyValuePair;);
                    for(var i=0,l=_3.length; i<l; i++)
                        b.push(fn(_3[i]));
                    buf.push("\"3\":[" + b.join(",") + "]");
                }

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(ReplaceAttributes obj) /*-{
                return true;
            }-*/;

            protected ReplaceAttributes() {}

            // getters and setters

            // empty

            public final native boolean getEmpty() /*-{
                return this["1"] || false;
            }-*/;

            public final native ReplaceAttributes setEmpty(boolean empty) /*-{
                this["1"] = empty;
                return this;
            }-*/;

            public final native void clearEmpty() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasEmpty() /*-{
                return this["1"] != null;
            }-*/;

            // oldAttribute

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> getOldAttributeArray() /*-{
                return this["2"];
            }-*/;

            public final java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> getOldAttributeList() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getOldAttributeArray();
                java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> list = new java.util.ArrayList<ProtocolDocumentOperation.Component.KeyValuePair>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getOldAttributeCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native ReplaceAttributes setOldAttributeArray(JsArray<ProtocolDocumentOperation.Component.KeyValuePair> oldAttribute) /*-{
                this["2"] = oldAttribute;
                return this;
            }-*/;

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> clearOldAttributeArray() /*-{
                return (this["2"] = []);
            }-*/;

            public final ProtocolDocumentOperation.Component.KeyValuePair getOldAttribute(int index) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getOldAttributeArray();
                return array == null ? null : array.get(index);
            }

            public final int getOldAttributeCount() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getOldAttributeArray();
                return array == null ? 0 : array.length();
            }

            public final void addOldAttribute(ProtocolDocumentOperation.Component.KeyValuePair oldAttribute) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getOldAttributeArray();
                if(array == null)
                    array = clearOldAttributeArray();
                array.push(oldAttribute);
            }

            // newAttribute

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> getNewAttributeArray() /*-{
                return this["3"];
            }-*/;

            public final java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> getNewAttributeList() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getNewAttributeArray();
                java.util.List<ProtocolDocumentOperation.Component.KeyValuePair> list = new java.util.ArrayList<ProtocolDocumentOperation.Component.KeyValuePair>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getNewAttributeCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native ReplaceAttributes setNewAttributeArray(JsArray<ProtocolDocumentOperation.Component.KeyValuePair> newAttribute) /*-{
                this["3"] = newAttribute;
                return this;
            }-*/;

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValuePair> clearNewAttributeArray() /*-{
                return (this["3"] = []);
            }-*/;

            public final ProtocolDocumentOperation.Component.KeyValuePair getNewAttribute(int index) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getNewAttributeArray();
                return array == null ? null : array.get(index);
            }

            public final int getNewAttributeCount() {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getNewAttributeArray();
                return array == null ? 0 : array.length();
            }

            public final void addNewAttribute(ProtocolDocumentOperation.Component.KeyValuePair newAttribute) {
                JsArray<ProtocolDocumentOperation.Component.KeyValuePair> array = getNewAttributeArray();
                if(array == null)
                    array = clearNewAttributeArray();
                array.push(newAttribute);
            }


        }public static class UpdateAttributes extends JavaScriptObject  {


            public static class Builder extends UpdateAttributes {
              protected Builder() { }
              public final UpdateAttributes build() {
                return (UpdateAttributes)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new UpdateAttributes instance 
             *
             * @return new UpdateAttributes instance
             */
            public static native UpdateAttributes create() /*-{
                return {
                  "_protoMessageName": "UpdateAttributes",              
                };
            }-*/;

            /**
             * Creates a new JsArray<UpdateAttributes> instance 
             *
             * @return new JsArray<UpdateAttributes> instance
             */
            public static native JsArray<UpdateAttributes> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a UpdateAttributes (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return UpdateAttributes
             */
            public static native UpdateAttributes get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<UpdateAttributes> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<UpdateAttributes> 
             */
            public static native JsArray<UpdateAttributes> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a UpdateAttributes from a json string
             *
             * @param json string to be parsed/evaluated
             * @return UpdateAttributes 
             */
            public static native UpdateAttributes parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<UpdateAttributes> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<UpdateAttributes> 
             */
            public static native JsArray<UpdateAttributes> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param UpdateAttributes the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(UpdateAttributes obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":" + _1);
                var _2 = obj["2"];
                if(_2 != null && _2.length != 0) {
                    var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.KeyValueUpdate::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$KeyValueUpdate;);
                    for(var i=0,l=_2.length; i<l; i++)
                        b.push(fn(_2[i]));
                    buf.push("\"2\":[" + b.join(",") + "]");
                }

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(UpdateAttributes obj) /*-{
                return true;
            }-*/;

            protected UpdateAttributes() {}

            // getters and setters

            // empty

            public final native boolean getEmpty() /*-{
                return this["1"] || false;
            }-*/;

            public final native UpdateAttributes setEmpty(boolean empty) /*-{
                this["1"] = empty;
                return this;
            }-*/;

            public final native void clearEmpty() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasEmpty() /*-{
                return this["1"] != null;
            }-*/;

            // attributeUpdate

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> getAttributeUpdateArray() /*-{
                return this["2"];
            }-*/;

            public final java.util.List<ProtocolDocumentOperation.Component.KeyValueUpdate> getAttributeUpdateList() {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getAttributeUpdateArray();
                java.util.List<ProtocolDocumentOperation.Component.KeyValueUpdate> list = new java.util.ArrayList<ProtocolDocumentOperation.Component.KeyValueUpdate>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getAttributeUpdateCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native UpdateAttributes setAttributeUpdateArray(JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> attributeUpdate) /*-{
                this["2"] = attributeUpdate;
                return this;
            }-*/;

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> clearAttributeUpdateArray() /*-{
                return (this["2"] = []);
            }-*/;

            public final ProtocolDocumentOperation.Component.KeyValueUpdate getAttributeUpdate(int index) {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getAttributeUpdateArray();
                return array == null ? null : array.get(index);
            }

            public final int getAttributeUpdateCount() {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getAttributeUpdateArray();
                return array == null ? 0 : array.length();
            }

            public final void addAttributeUpdate(ProtocolDocumentOperation.Component.KeyValueUpdate attributeUpdate) {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getAttributeUpdateArray();
                if(array == null)
                    array = clearAttributeUpdateArray();
                array.push(attributeUpdate);
            }


        }public static class AnnotationBoundary extends JavaScriptObject  {


            public static class Builder extends AnnotationBoundary {
              protected Builder() { }
              public final AnnotationBoundary build() {
                return (AnnotationBoundary)this;
              }
              public static native Builder create() /*-{
                return {
                };
              }-*/;
            }

            public static final Builder newBuilder() {
              return Builder.create();
            }
            
            /**
             * Creates a new AnnotationBoundary instance 
             *
             * @return new AnnotationBoundary instance
             */
            public static native AnnotationBoundary create() /*-{
                return {
                  "_protoMessageName": "AnnotationBoundary",              
                };
            }-*/;

            /**
             * Creates a new JsArray<AnnotationBoundary> instance 
             *
             * @return new JsArray<AnnotationBoundary> instance
             */
            public static native JsArray<AnnotationBoundary> createArray() /*-{
                return [];
            }-*/;

            /**
             * Returns the name of this protocol buffer.
             */
            public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
                return instance._protoMessageName;
            }-*/;

            /**
             * Gets a AnnotationBoundary (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return AnnotationBoundary
             */
            public static native AnnotationBoundary get(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Gets a JsArray<AnnotationBoundary> (casting) from a JavaScriptObject
             *
             * @param JavaScriptObject to cast
             * @return JsArray<AnnotationBoundary> 
             */
            public static native JsArray<AnnotationBoundary> getArray(JavaScriptObject jso) /*-{
                return jso;
            }-*/;

            /**
             * Parses a AnnotationBoundary from a json string
             *
             * @param json string to be parsed/evaluated
             * @return AnnotationBoundary 
             */
            public static native AnnotationBoundary parse(String json) /*-{
                return eval("(" + json + ")");
            }-*/;

            /**
             * Parses a JsArray<AnnotationBoundary> from a json string
             *
             * @param json string to be parsed/evaluated
             * @return JsArray<AnnotationBoundary> 
             */
            public static native JsArray<AnnotationBoundary> parseArray(String json) /*-{
                return eval("(" + json + ")");
            }-*/;
            
            /**
             * Serializes a json object to a json string.
             *
             * @param AnnotationBoundary the object to serialize
             * @return String the serialized json string
             */
            public static native String stringify(AnnotationBoundary obj) /*-{
                var buf = [];
                var _1 = obj["1"];
                if(_1 != null)
                    buf.push("\"1\":" + _1);
                var _2 = obj["2"];
                if(_2 != null && _2.length != 0) {
                    buf.push("\"2\":[\"" + _2.join("\",\"") + "\"]");
                }
                var _3 = obj["3"];
                if(_3 != null && _3.length != 0) {
                    var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.KeyValueUpdate::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$KeyValueUpdate;);
                    for(var i=0,l=_3.length; i<l; i++)
                        b.push(fn(_3[i]));
                    buf.push("\"3\":[" + b.join(",") + "]");
                }

                return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
            }-*/;
            
            public static native boolean isInitialized(AnnotationBoundary obj) /*-{
                return true;
            }-*/;

            protected AnnotationBoundary() {}

            // getters and setters

            // empty

            public final native boolean getEmpty() /*-{
                return this["1"] || false;
            }-*/;

            public final native AnnotationBoundary setEmpty(boolean empty) /*-{
                this["1"] = empty;
                return this;
            }-*/;

            public final native void clearEmpty() /*-{
                delete this["1"];
            }-*/;

            public final native boolean hasEmpty() /*-{
                return this["1"] != null;
            }-*/;

            // end

            public final native JsArrayString getEndArray() /*-{
                return this["2"];
            }-*/;

            public final java.util.List<String> getEndList() {
                JsArrayString array = getEndArray();
                java.util.List<String> list = new java.util.ArrayList<String>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getEndCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native AnnotationBoundary setEndArray(JsArrayString end) /*-{
                this["2"] = end;
                return this;
            }-*/;

            public final native JsArrayString clearEndArray() /*-{
                return (this["2"] = []);
            }-*/;

            public final String getEnd(int index) {
                JsArrayString array = getEndArray();
                return array == null ? null : array.get(index);
            }

            public final int getEndCount() {
                JsArrayString array = getEndArray();
                return array == null ? 0 : array.length();
            }

            public final void addEnd(String end) {
                JsArrayString array = getEndArray();
                if(array == null)
                    array = clearEndArray();
                array.push(end);
            }

            // change

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> getChangeArray() /*-{
                return this["3"];
            }-*/;

            public final java.util.List<ProtocolDocumentOperation.Component.KeyValueUpdate> getChangeList() {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getChangeArray();
                java.util.List<ProtocolDocumentOperation.Component.KeyValueUpdate> list = new java.util.ArrayList<ProtocolDocumentOperation.Component.KeyValueUpdate>();
                
                if (array == null) {
                  return null; 
                }
                for (int i=0; i < getChangeCount(); i++) {
                  list.add(array.get(i));
                }
                return list;
            }

            public final native AnnotationBoundary setChangeArray(JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> change) /*-{
                this["3"] = change;
                return this;
            }-*/;

            public final native JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> clearChangeArray() /*-{
                return (this["3"] = []);
            }-*/;

            public final ProtocolDocumentOperation.Component.KeyValueUpdate getChange(int index) {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getChangeArray();
                return array == null ? null : array.get(index);
            }

            public final int getChangeCount() {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getChangeArray();
                return array == null ? 0 : array.length();
            }

            public final void addChange(ProtocolDocumentOperation.Component.KeyValueUpdate change) {
                JsArray<ProtocolDocumentOperation.Component.KeyValueUpdate> array = getChangeArray();
                if(array == null)
                    array = clearChangeArray();
                array.push(change);
            }


        }

        public static class Builder extends Component {
          protected Builder() { }
          public final Component build() {
            return (Component)this;
          }
          public static native Builder create() /*-{
            return {
            };
          }-*/;
        }

        public static final Builder newBuilder() {
          return Builder.create();
        }
        
        /**
         * Creates a new Component instance 
         *
         * @return new Component instance
         */
        public static native Component create() /*-{
            return {
              "_protoMessageName": "Component",              
            };
        }-*/;

        /**
         * Creates a new JsArray<Component> instance 
         *
         * @return new JsArray<Component> instance
         */
        public static native JsArray<Component> createArray() /*-{
            return [];
        }-*/;

        /**
         * Returns the name of this protocol buffer.
         */
        public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
            return instance._protoMessageName;
        }-*/;

        /**
         * Gets a Component (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Component
         */
        public static native Component get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Gets a JsArray<Component> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Component> 
         */
        public static native JsArray<Component> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;

        /**
         * Parses a Component from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Component 
         */
        public static native Component parse(String json) /*-{
            return eval("(" + json + ")");
        }-*/;

        /**
         * Parses a JsArray<Component> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Component> 
         */
        public static native JsArray<Component> parseArray(String json) /*-{
            return eval("(" + json + ")");
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Component the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Component obj) /*-{
            var buf = [];
            var _1 = obj["1"];
            if(_1 != null)
                buf.push("\"1\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.AnnotationBoundary::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$AnnotationBoundary;)(_1));
            var _2 = obj["2"];
            if(_2 != null)
                buf.push("\"2\":\"" + _2 + "\"");
            var _3 = obj["3"];
            if(_3 != null)
                buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.ElementStart::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$ElementStart;)(_3));
            var _4 = obj["4"];
            if(_4 != null)
                buf.push("\"4\":" + _4);
            var _5 = obj["5"];
            if(_5 != null)
                buf.push("\"5\":" + _5);
            var _6 = obj["6"];
            if(_6 != null)
                buf.push("\"6\":\"" + _6 + "\"");
            var _7 = obj["7"];
            if(_7 != null)
                buf.push("\"7\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.ElementStart::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$ElementStart;)(_7));
            var _8 = obj["8"];
            if(_8 != null)
                buf.push("\"8\":" + _8);
            var _9 = obj["9"];
            if(_9 != null)
                buf.push("\"9\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.ReplaceAttributes::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$ReplaceAttributes;)(_9));
            var _10 = obj["10"];
            if(_10 != null)
                buf.push("\"10\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component.UpdateAttributes::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component$UpdateAttributes;)(_10));

            return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
        }-*/;
        
        public static native boolean isInitialized(Component obj) /*-{
            return true;
        }-*/;

        protected Component() {}

        // getters and setters

        // annotationBoundary

        public final native AnnotationBoundary getAnnotationBoundary() /*-{
            return this["1"];
        }-*/;

        public final native Component setAnnotationBoundary(AnnotationBoundary annotationBoundary) /*-{
            this["1"] = annotationBoundary;
            return this;
        }-*/;

        public final native void clearAnnotationBoundary() /*-{
            delete this["1"];
        }-*/;

        public final native boolean hasAnnotationBoundary() /*-{
            return this["1"] != null;
        }-*/;

        // characters

        public final native String getCharacters() /*-{
            return this["2"] || "";
        }-*/;

        public final native Component setCharacters(String characters) /*-{
            this["2"] = characters;
            return this;
        }-*/;

        public final native void clearCharacters() /*-{
            delete this["2"];
        }-*/;

        public final native boolean hasCharacters() /*-{
            return this["2"] != null;
        }-*/;

        // elementStart

        public final native ElementStart getElementStart() /*-{
            return this["3"];
        }-*/;

        public final native Component setElementStart(ElementStart elementStart) /*-{
            this["3"] = elementStart;
            return this;
        }-*/;

        public final native void clearElementStart() /*-{
            delete this["3"];
        }-*/;

        public final native boolean hasElementStart() /*-{
            return this["3"] != null;
        }-*/;

        // elementEnd

        public final native boolean getElementEnd() /*-{
            return this["4"] || false;
        }-*/;

        public final native Component setElementEnd(boolean elementEnd) /*-{
            this["4"] = elementEnd;
            return this;
        }-*/;

        public final native void clearElementEnd() /*-{
            delete this["4"];
        }-*/;

        public final native boolean hasElementEnd() /*-{
            return this["4"] != null;
        }-*/;

        // retainItemCount

        public final native int getRetainItemCount() /*-{
            return this["5"] || 0;
        }-*/;

        public final native Component setRetainItemCount(int retainItemCount) /*-{
            this["5"] = retainItemCount;
            return this;
        }-*/;

        public final native void clearRetainItemCount() /*-{
            delete this["5"];
        }-*/;

        public final native boolean hasRetainItemCount() /*-{
            return this["5"] != null;
        }-*/;

        // deleteCharacters

        public final native String getDeleteCharacters() /*-{
            return this["6"] || "";
        }-*/;

        public final native Component setDeleteCharacters(String deleteCharacters) /*-{
            this["6"] = deleteCharacters;
            return this;
        }-*/;

        public final native void clearDeleteCharacters() /*-{
            delete this["6"];
        }-*/;

        public final native boolean hasDeleteCharacters() /*-{
            return this["6"] != null;
        }-*/;

        // deleteElementStart

        public final native ElementStart getDeleteElementStart() /*-{
            return this["7"];
        }-*/;

        public final native Component setDeleteElementStart(ElementStart deleteElementStart) /*-{
            this["7"] = deleteElementStart;
            return this;
        }-*/;

        public final native void clearDeleteElementStart() /*-{
            delete this["7"];
        }-*/;

        public final native boolean hasDeleteElementStart() /*-{
            return this["7"] != null;
        }-*/;

        // deleteElementEnd

        public final native boolean getDeleteElementEnd() /*-{
            return this["8"] || false;
        }-*/;

        public final native Component setDeleteElementEnd(boolean deleteElementEnd) /*-{
            this["8"] = deleteElementEnd;
            return this;
        }-*/;

        public final native void clearDeleteElementEnd() /*-{
            delete this["8"];
        }-*/;

        public final native boolean hasDeleteElementEnd() /*-{
            return this["8"] != null;
        }-*/;

        // replaceAttributes

        public final native ReplaceAttributes getReplaceAttributes() /*-{
            return this["9"];
        }-*/;

        public final native Component setReplaceAttributes(ReplaceAttributes replaceAttributes) /*-{
            this["9"] = replaceAttributes;
            return this;
        }-*/;

        public final native void clearReplaceAttributes() /*-{
            delete this["9"];
        }-*/;

        public final native boolean hasReplaceAttributes() /*-{
            return this["9"] != null;
        }-*/;

        // updateAttributes

        public final native UpdateAttributes getUpdateAttributes() /*-{
            return this["10"];
        }-*/;

        public final native Component setUpdateAttributes(UpdateAttributes updateAttributes) /*-{
            this["10"] = updateAttributes;
            return this;
        }-*/;

        public final native void clearUpdateAttributes() /*-{
            delete this["10"];
        }-*/;

        public final native boolean hasUpdateAttributes() /*-{
            return this["10"] != null;
        }-*/;


    }

    public static class Builder extends ProtocolDocumentOperation {
      protected Builder() { }
      public final ProtocolDocumentOperation build() {
        return (ProtocolDocumentOperation)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolDocumentOperation instance 
     *
     * @return new ProtocolDocumentOperation instance
     */
    public static native ProtocolDocumentOperation create() /*-{
        return {
          "_protoMessageName": "ProtocolDocumentOperation",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolDocumentOperation> instance 
     *
     * @return new JsArray<ProtocolDocumentOperation> instance
     */
    public static native JsArray<ProtocolDocumentOperation> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolDocumentOperation (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolDocumentOperation
     */
    public static native ProtocolDocumentOperation get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolDocumentOperation> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolDocumentOperation> 
     */
    public static native JsArray<ProtocolDocumentOperation> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolDocumentOperation from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolDocumentOperation 
     */
    public static native ProtocolDocumentOperation parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolDocumentOperation> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolDocumentOperation> 
     */
    public static native JsArray<ProtocolDocumentOperation> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolDocumentOperation the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolDocumentOperation obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null && _1.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.federation.ProtocolDocumentOperation.Component::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation$Component;);
            for(var i=0,l=_1.length; i<l; i++)
                b.push(fn(_1[i]));
            buf.push("\"1\":[" + b.join(",") + "]");
        }

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolDocumentOperation obj) /*-{
        return true;
    }-*/;

    protected ProtocolDocumentOperation() {}

    // getters and setters

    // component

    public final native JsArray<Component> getComponentArray() /*-{
        return this["1"];
    }-*/;

    public final java.util.List<Component> getComponentList() {
        JsArray<Component> array = getComponentArray();
        java.util.List<Component> list = new java.util.ArrayList<Component>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getComponentCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolDocumentOperation setComponentArray(JsArray<Component> component) /*-{
        this["1"] = component;
        return this;
    }-*/;

    public final native JsArray<Component> clearComponentArray() /*-{
        return (this["1"] = []);
    }-*/;

    public final Component getComponent(int index) {
        JsArray<Component> array = getComponentArray();
        return array == null ? null : array.get(index);
    }

    public final int getComponentCount() {
        JsArray<Component> array = getComponentArray();
        return array == null ? 0 : array.length();
    }

    public final void addComponent(Component component) {
        JsArray<Component> array = getComponentArray();
        if(array == null)
            array = clearComponentArray();
        array.push(component);
    }


}