// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class CloseWaveletChannelRequest extends JavaScriptObject  {


    public static class Builder extends CloseWaveletChannelRequest {
      protected Builder() { }
      public final CloseWaveletChannelRequest build() {
        return (CloseWaveletChannelRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new CloseWaveletChannelRequest instance 
     *
     * @return new CloseWaveletChannelRequest instance
     */
    public static native CloseWaveletChannelRequest create() /*-{
        return {
          "_protoMessageName": "CloseWaveletChannelRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<CloseWaveletChannelRequest> instance 
     *
     * @return new JsArray<CloseWaveletChannelRequest> instance
     */
    public static native JsArray<CloseWaveletChannelRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a CloseWaveletChannelRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return CloseWaveletChannelRequest
     */
    public static native CloseWaveletChannelRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<CloseWaveletChannelRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<CloseWaveletChannelRequest> 
     */
    public static native JsArray<CloseWaveletChannelRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a CloseWaveletChannelRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return CloseWaveletChannelRequest 
     */
    public static native CloseWaveletChannelRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<CloseWaveletChannelRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<CloseWaveletChannelRequest> 
     */
    public static native JsArray<CloseWaveletChannelRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param CloseWaveletChannelRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(CloseWaveletChannelRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(CloseWaveletChannelRequest obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected CloseWaveletChannelRequest() {}

    // getters and setters

    // channelId

    public final native String getChannelId() /*-{
        return this["1"] || "";
    }-*/;

    public final native CloseWaveletChannelRequest setChannelId(String channelId) /*-{
        this["1"] = channelId;
        return this;
    }-*/;

    public final native void clearChannelId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasChannelId() /*-{
        return this["1"] != null;
    }-*/;


}