// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class FetchWaveViewRequest extends JavaScriptObject  {


    public static class Builder extends FetchWaveViewRequest {
      protected Builder() { }
      public final FetchWaveViewRequest build() {
        return (FetchWaveViewRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new FetchWaveViewRequest instance 
     *
     * @return new FetchWaveViewRequest instance
     */
    public static native FetchWaveViewRequest create() /*-{
        return {
          "_protoMessageName": "FetchWaveViewRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<FetchWaveViewRequest> instance 
     *
     * @return new JsArray<FetchWaveViewRequest> instance
     */
    public static native JsArray<FetchWaveViewRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a FetchWaveViewRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return FetchWaveViewRequest
     */
    public static native FetchWaveViewRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<FetchWaveViewRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<FetchWaveViewRequest> 
     */
    public static native JsArray<FetchWaveViewRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a FetchWaveViewRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return FetchWaveViewRequest 
     */
    public static native FetchWaveViewRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<FetchWaveViewRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<FetchWaveViewRequest> 
     */
    public static native JsArray<FetchWaveViewRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param FetchWaveViewRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(FetchWaveViewRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null && _2.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.concurrencycontrol.WaveletVersion::stringify(Lorg/waveprotocol/wave/concurrencycontrol/WaveletVersion;);
            for(var i=0,l=_2.length; i<l; i++)
                b.push(fn(_2[i]));
            buf.push("\"2\":[" + b.join(",") + "]");
        }

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(FetchWaveViewRequest obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected FetchWaveViewRequest() {}

    // getters and setters

    // waveId

    public final native String getWaveId() /*-{
        return this["1"] || "";
    }-*/;

    public final native FetchWaveViewRequest setWaveId(String waveId) /*-{
        this["1"] = waveId;
        return this;
    }-*/;

    public final native void clearWaveId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveId() /*-{
        return this["1"] != null;
    }-*/;

    // knownWavelet

    public final native JsArray<WaveletVersion> getKnownWaveletArray() /*-{
        return this["2"];
    }-*/;

    public final java.util.List<WaveletVersion> getKnownWaveletList() {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        java.util.List<WaveletVersion> list = new java.util.ArrayList<WaveletVersion>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getKnownWaveletCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native FetchWaveViewRequest setKnownWaveletArray(JsArray<WaveletVersion> knownWavelet) /*-{
        this["2"] = knownWavelet;
        return this;
    }-*/;

    public final native JsArray<WaveletVersion> clearKnownWaveletArray() /*-{
        return (this["2"] = []);
    }-*/;

    public final WaveletVersion getKnownWavelet(int index) {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        return array == null ? null : array.get(index);
    }

    public final int getKnownWaveletCount() {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        return array == null ? 0 : array.length();
    }

    public final void addKnownWavelet(WaveletVersion knownWavelet) {
        JsArray<WaveletVersion> array = getKnownWaveletArray();
        if(array == null)
            array = clearKnownWaveletArray();
        array.push(knownWavelet);
    }


}