// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class OpenWaveletChannelRequest extends JavaScriptObject  {


    public static class Builder extends OpenWaveletChannelRequest {
      protected Builder() { }
      public final OpenWaveletChannelRequest build() {
        return (OpenWaveletChannelRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new OpenWaveletChannelRequest instance 
     *
     * @return new OpenWaveletChannelRequest instance
     */
    public static native OpenWaveletChannelRequest create() /*-{
        return {
          "_protoMessageName": "OpenWaveletChannelRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<OpenWaveletChannelRequest> instance 
     *
     * @return new JsArray<OpenWaveletChannelRequest> instance
     */
    public static native JsArray<OpenWaveletChannelRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a OpenWaveletChannelRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return OpenWaveletChannelRequest
     */
    public static native OpenWaveletChannelRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<OpenWaveletChannelRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<OpenWaveletChannelRequest> 
     */
    public static native JsArray<OpenWaveletChannelRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a OpenWaveletChannelRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return OpenWaveletChannelRequest 
     */
    public static native OpenWaveletChannelRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<OpenWaveletChannelRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<OpenWaveletChannelRequest> 
     */
    public static native JsArray<OpenWaveletChannelRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param OpenWaveletChannelRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(OpenWaveletChannelRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_3));

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(OpenWaveletChannelRequest obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null 
            && obj["3"] != null;
    }-*/;

    protected OpenWaveletChannelRequest() {}

    // getters and setters

    // waveId

    public final native String getWaveId() /*-{
        return this["1"] || "";
    }-*/;

    public final native OpenWaveletChannelRequest setWaveId(String waveId) /*-{
        this["1"] = waveId;
        return this;
    }-*/;

    public final native void clearWaveId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveId() /*-{
        return this["1"] != null;
    }-*/;

    // waveletId

    public final native String getWaveletId() /*-{
        return this["2"] || "";
    }-*/;

    public final native OpenWaveletChannelRequest setWaveletId(String waveletId) /*-{
        this["2"] = waveletId;
        return this;
    }-*/;

    public final native void clearWaveletId() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasWaveletId() /*-{
        return this["2"] != null;
    }-*/;

    // beginVersion

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getBeginVersion() /*-{
        return this["3"];
    }-*/;

    public final native OpenWaveletChannelRequest setBeginVersion(org.waveprotocol.wave.federation.ProtocolHashedVersion beginVersion) /*-{
        this["3"] = beginVersion;
        return this;
    }-*/;

    public final native void clearBeginVersion() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasBeginVersion() /*-{
        return this["3"] != null;
    }-*/;


}