// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class ResponseStatus extends JavaScriptObject  {

    public static class ResponseCode extends JavaScriptObject {
            
        public static final ResponseCode OK = create(0);
        public static final ResponseCode BAD_REQUEST = create(1);
        public static final ResponseCode INTERNAL_ERROR = create(2);
        public static final ResponseCode NOT_AUTHORIZED = create(3);
        public static final ResponseCode VERSION_ERROR = create(4);
        public static final ResponseCode INVALID_OPERATION = create(5);
        public static final ResponseCode SCHEMA_VIOLATION = create(6);
        public static final ResponseCode SIZE_LIMIT_EXCEEDED = create(7);
        public static final ResponseCode POLICY_VIOLATION = create(8);
        public static final ResponseCode QUARANTINED = create(9);
        public static final ResponseCode TOO_OLD = create(10);
        
        private static native ResponseCode create(int number) /*-{
            return number;
        }-*/;
        
        protected ResponseCode() {}

        public final native int getNumber() /*-{
            return this;
        }-*/;
        
    }


    public static class Builder extends ResponseStatus {
      protected Builder() { }
      public final ResponseStatus build() {
        return (ResponseStatus)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ResponseStatus instance 
     *
     * @return new ResponseStatus instance
     */
    public static native ResponseStatus create() /*-{
        return {
          "_protoMessageName": "ResponseStatus",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ResponseStatus> instance 
     *
     * @return new JsArray<ResponseStatus> instance
     */
    public static native JsArray<ResponseStatus> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ResponseStatus (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ResponseStatus
     */
    public static native ResponseStatus get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ResponseStatus> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ResponseStatus> 
     */
    public static native JsArray<ResponseStatus> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ResponseStatus from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ResponseStatus 
     */
    public static native ResponseStatus parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ResponseStatus> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ResponseStatus> 
     */
    public static native JsArray<ResponseStatus> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ResponseStatus the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ResponseStatus obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + _1);
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ResponseStatus obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected ResponseStatus() {}

    // getters and setters

    // status

    public final native ResponseCode getStatus() /*-{
        var v = this["1"];
        return v == null ? 0 : v;
    }-*/;

    public final native ResponseStatus setStatus(ResponseCode status) /*-{
        this["1"] = status;
        return this;
    }-*/;

    public final native void clearStatus() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasStatus() /*-{
        return this["1"] != null;
    }-*/;

    // failureReason

    public final native String getFailureReason() /*-{
        return this["2"] || "";
    }-*/;

    public final native ResponseStatus setFailureReason(String failureReason) /*-{
        this["2"] = failureReason;
        return this;
    }-*/;

    public final native void clearFailureReason() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasFailureReason() /*-{
        return this["2"] != null;
    }-*/;


}