// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class SubmitDeltaResponse extends JavaScriptObject  {


    public static class Builder extends SubmitDeltaResponse {
      protected Builder() { }
      public final SubmitDeltaResponse build() {
        return (SubmitDeltaResponse)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new SubmitDeltaResponse instance 
     *
     * @return new SubmitDeltaResponse instance
     */
    public static native SubmitDeltaResponse create() /*-{
        return {
          "_protoMessageName": "SubmitDeltaResponse",              
        };
    }-*/;

    /**
     * Creates a new JsArray<SubmitDeltaResponse> instance 
     *
     * @return new JsArray<SubmitDeltaResponse> instance
     */
    public static native JsArray<SubmitDeltaResponse> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a SubmitDeltaResponse (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return SubmitDeltaResponse
     */
    public static native SubmitDeltaResponse get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<SubmitDeltaResponse> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<SubmitDeltaResponse> 
     */
    public static native JsArray<SubmitDeltaResponse> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a SubmitDeltaResponse from a json string
     *
     * @param json string to be parsed/evaluated
     * @return SubmitDeltaResponse 
     */
    public static native SubmitDeltaResponse parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<SubmitDeltaResponse> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<SubmitDeltaResponse> 
     */
    public static native JsArray<SubmitDeltaResponse> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param SubmitDeltaResponse the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(SubmitDeltaResponse obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + @org.waveprotocol.wave.concurrencycontrol.ResponseStatus::stringify(Lorg/waveprotocol/wave/concurrencycontrol/ResponseStatus;)(_1));
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + _2);
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_3));
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":" + _4);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(SubmitDeltaResponse obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected SubmitDeltaResponse() {}

    // getters and setters

    // status

    public final native ResponseStatus getStatus() /*-{
        return this["1"];
    }-*/;

    public final native SubmitDeltaResponse setStatus(ResponseStatus status) /*-{
        this["1"] = status;
        return this;
    }-*/;

    public final native void clearStatus() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasStatus() /*-{
        return this["1"] != null;
    }-*/;

    // operationsApplied

    public final native int getOperationsApplied() /*-{
        return this["2"] || 0;
    }-*/;

    public final native SubmitDeltaResponse setOperationsApplied(int operationsApplied) /*-{
        this["2"] = operationsApplied;
        return this;
    }-*/;

    public final native void clearOperationsApplied() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasOperationsApplied() /*-{
        return this["2"] != null;
    }-*/;

    // hashedVersionAfterApplication

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getHashedVersionAfterApplication() /*-{
        return this["3"];
    }-*/;

    public final native SubmitDeltaResponse setHashedVersionAfterApplication(org.waveprotocol.wave.federation.ProtocolHashedVersion hashedVersionAfterApplication) /*-{
        this["3"] = hashedVersionAfterApplication;
        return this;
    }-*/;

    public final native void clearHashedVersionAfterApplication() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasHashedVersionAfterApplication() /*-{
        return this["3"] != null;
    }-*/;

    // timestampAfterApplication

    public final native double getTimestampAfterApplication() /*-{
        return this["4"] || 0;
    }-*/;

    public final native SubmitDeltaResponse setTimestampAfterApplication(double timestampAfterApplication) /*-{
        this["4"] = timestampAfterApplication;
        return this;
    }-*/;

    public final native void clearTimestampAfterApplication() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasTimestampAfterApplication() /*-{
        return this["4"] != null;
    }-*/;


}