// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class SubmitDeltaRequest extends JavaScriptObject  {


    public static class Builder extends SubmitDeltaRequest {
      protected Builder() { }
      public final SubmitDeltaRequest build() {
        return (SubmitDeltaRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new SubmitDeltaRequest instance 
     *
     * @return new SubmitDeltaRequest instance
     */
    public static native SubmitDeltaRequest create() /*-{
        return {
          "_protoMessageName": "SubmitDeltaRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<SubmitDeltaRequest> instance 
     *
     * @return new JsArray<SubmitDeltaRequest> instance
     */
    public static native JsArray<SubmitDeltaRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a SubmitDeltaRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return SubmitDeltaRequest
     */
    public static native SubmitDeltaRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<SubmitDeltaRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<SubmitDeltaRequest> 
     */
    public static native JsArray<SubmitDeltaRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a SubmitDeltaRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return SubmitDeltaRequest 
     */
    public static native SubmitDeltaRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<SubmitDeltaRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<SubmitDeltaRequest> 
     */
    public static native JsArray<SubmitDeltaRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param SubmitDeltaRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(SubmitDeltaRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolWaveletDelta::stringify(Lorg/waveprotocol/wave/federation/ProtocolWaveletDelta;)(_3));
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":\"" + _4 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(SubmitDeltaRequest obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null 
            && obj["3"] != null 
            && obj["4"] != null;
    }-*/;

    protected SubmitDeltaRequest() {}

    // getters and setters

    // waveId

    public final native String getWaveId() /*-{
        return this["1"] || "";
    }-*/;

    public final native SubmitDeltaRequest setWaveId(String waveId) /*-{
        this["1"] = waveId;
        return this;
    }-*/;

    public final native void clearWaveId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveId() /*-{
        return this["1"] != null;
    }-*/;

    // waveletId

    public final native String getWaveletId() /*-{
        return this["2"] || "";
    }-*/;

    public final native SubmitDeltaRequest setWaveletId(String waveletId) /*-{
        this["2"] = waveletId;
        return this;
    }-*/;

    public final native void clearWaveletId() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasWaveletId() /*-{
        return this["2"] != null;
    }-*/;

    // delta

    public final native org.waveprotocol.wave.federation.ProtocolWaveletDelta getDelta() /*-{
        return this["3"];
    }-*/;

    public final native SubmitDeltaRequest setDelta(org.waveprotocol.wave.federation.ProtocolWaveletDelta delta) /*-{
        this["3"] = delta;
        return this;
    }-*/;

    public final native void clearDelta() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasDelta() /*-{
        return this["3"] != null;
    }-*/;

    // channelId

    public final native String getChannelId() /*-{
        return this["4"] || "";
    }-*/;

    public final native SubmitDeltaRequest setChannelId(String channelId) /*-{
        this["4"] = channelId;
        return this;
    }-*/;

    public final native void clearChannelId() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasChannelId() /*-{
        return this["4"] != null;
    }-*/;


}