// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class Terminator extends JavaScriptObject  {


    public static class Builder extends Terminator {
      protected Builder() { }
      public final Terminator build() {
        return (Terminator)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new Terminator instance 
     *
     * @return new Terminator instance
     */
    public static native Terminator create() /*-{
        return {
          "_protoMessageName": "Terminator",              
        };
    }-*/;

    /**
     * Creates a new JsArray<Terminator> instance 
     *
     * @return new JsArray<Terminator> instance
     */
    public static native JsArray<Terminator> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a Terminator (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return Terminator
     */
    public static native Terminator get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<Terminator> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<Terminator> 
     */
    public static native JsArray<Terminator> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a Terminator from a json string
     *
     * @param json string to be parsed/evaluated
     * @return Terminator 
     */
    public static native Terminator parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<Terminator> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<Terminator> 
     */
    public static native JsArray<Terminator> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param Terminator the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(Terminator obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + _1);
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":\"" + _2 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(Terminator obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected Terminator() {}

    // getters and setters

    // responseCode

    public final native int getResponseCode() /*-{
        return this["1"] || 0;
    }-*/;

    public final native Terminator setResponseCode(int responseCode) /*-{
        this["1"] = responseCode;
        return this;
    }-*/;

    public final native void clearResponseCode() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasResponseCode() /*-{
        return this["1"] != null;
    }-*/;

    // errorMessage

    public final native String getErrorMessage() /*-{
        return this["2"] || "";
    }-*/;

    public final native Terminator setErrorMessage(String errorMessage) /*-{
        this["2"] = errorMessage;
        return this;
    }-*/;

    public final native void clearErrorMessage() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasErrorMessage() /*-{
        return this["2"] != null;
    }-*/;


}