// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class TransportAuthenticationRequest extends JavaScriptObject  {


    public static class Builder extends TransportAuthenticationRequest {
      protected Builder() { }
      public final TransportAuthenticationRequest build() {
        return (TransportAuthenticationRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new TransportAuthenticationRequest instance 
     *
     * @return new TransportAuthenticationRequest instance
     */
    public static native TransportAuthenticationRequest create() /*-{
        return {
          "_protoMessageName": "TransportAuthenticationRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<TransportAuthenticationRequest> instance 
     *
     * @return new JsArray<TransportAuthenticationRequest> instance
     */
    public static native JsArray<TransportAuthenticationRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a TransportAuthenticationRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return TransportAuthenticationRequest
     */
    public static native TransportAuthenticationRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<TransportAuthenticationRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<TransportAuthenticationRequest> 
     */
    public static native JsArray<TransportAuthenticationRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a TransportAuthenticationRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return TransportAuthenticationRequest 
     */
    public static native TransportAuthenticationRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<TransportAuthenticationRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<TransportAuthenticationRequest> 
     */
    public static native JsArray<TransportAuthenticationRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param TransportAuthenticationRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(TransportAuthenticationRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(TransportAuthenticationRequest obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected TransportAuthenticationRequest() {}

    // getters and setters

    // token

    public final native String getToken() /*-{
        return this["1"] || "";
    }-*/;

    public final native TransportAuthenticationRequest setToken(String token) /*-{
        this["1"] = token;
        return this;
    }-*/;

    public final native void clearToken() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasToken() /*-{
        return this["1"] != null;
    }-*/;


}