// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class WaveletChannelTerminator extends JavaScriptObject  {


    public static class Builder extends WaveletChannelTerminator {
      protected Builder() { }
      public final WaveletChannelTerminator build() {
        return (WaveletChannelTerminator)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new WaveletChannelTerminator instance 
     *
     * @return new WaveletChannelTerminator instance
     */
    public static native WaveletChannelTerminator create() /*-{
        return {
          "_protoMessageName": "WaveletChannelTerminator",              
        };
    }-*/;

    /**
     * Creates a new JsArray<WaveletChannelTerminator> instance 
     *
     * @return new JsArray<WaveletChannelTerminator> instance
     */
    public static native JsArray<WaveletChannelTerminator> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a WaveletChannelTerminator (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return WaveletChannelTerminator
     */
    public static native WaveletChannelTerminator get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<WaveletChannelTerminator> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<WaveletChannelTerminator> 
     */
    public static native JsArray<WaveletChannelTerminator> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a WaveletChannelTerminator from a json string
     *
     * @param json string to be parsed/evaluated
     * @return WaveletChannelTerminator 
     */
    public static native WaveletChannelTerminator parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<WaveletChannelTerminator> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<WaveletChannelTerminator> 
     */
    public static native JsArray<WaveletChannelTerminator> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param WaveletChannelTerminator the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(WaveletChannelTerminator obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":" + @org.waveprotocol.wave.concurrencycontrol.ResponseStatus::stringify(Lorg/waveprotocol/wave/concurrencycontrol/ResponseStatus;)(_1));

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(WaveletChannelTerminator obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected WaveletChannelTerminator() {}

    // getters and setters

    // status

    public final native ResponseStatus getStatus() /*-{
        return this["1"];
    }-*/;

    public final native WaveletChannelTerminator setStatus(ResponseStatus status) /*-{
        this["1"] = status;
        return this;
    }-*/;

    public final native void clearStatus() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasStatus() /*-{
        return this["1"] != null;
    }-*/;


}