// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from clientserver.proto

package org.waveprotocol.wave.concurrencycontrol;

import com.google.gwt.core.client.*;

public class WaveletSnapshot extends JavaScriptObject  {


    public static class Builder extends WaveletSnapshot {
      protected Builder() { }
      public final WaveletSnapshot build() {
        return (WaveletSnapshot)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new WaveletSnapshot instance 
     *
     * @return new WaveletSnapshot instance
     */
    public static native WaveletSnapshot create() /*-{
        return {
          "_protoMessageName": "WaveletSnapshot",              
        };
    }-*/;

    /**
     * Creates a new JsArray<WaveletSnapshot> instance 
     *
     * @return new JsArray<WaveletSnapshot> instance
     */
    public static native JsArray<WaveletSnapshot> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a WaveletSnapshot (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return WaveletSnapshot
     */
    public static native WaveletSnapshot get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<WaveletSnapshot> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<WaveletSnapshot> 
     */
    public static native JsArray<WaveletSnapshot> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a WaveletSnapshot from a json string
     *
     * @param json string to be parsed/evaluated
     * @return WaveletSnapshot 
     */
    public static native WaveletSnapshot parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<WaveletSnapshot> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<WaveletSnapshot> 
     */
    public static native JsArray<WaveletSnapshot> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param WaveletSnapshot the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(WaveletSnapshot obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null && _2.length != 0) {
            buf.push("\"2\":[\"" + _2.join("\",\"") + "\"]");
        }
        var _3 = obj["3"];
        if(_3 != null && _3.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.concurrencycontrol.DocumentSnapshot::stringify(Lorg/waveprotocol/wave/concurrencycontrol/DocumentSnapshot;);
            for(var i=0,l=_3.length; i<l; i++)
                b.push(fn(_3[i]));
            buf.push("\"3\":[" + b.join(",") + "]");
        }
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_4));
        var _5 = obj["5"];
        if(_5 != null)
            buf.push("\"5\":" + _5);
        var _6 = obj["6"];
        if(_6 != null)
            buf.push("\"6\":\"" + _6 + "\"");
        var _7 = obj["7"];
        if(_7 != null)
            buf.push("\"7\":" + _7);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(WaveletSnapshot obj) /*-{
        return 
            obj["1"] != null 
            && obj["4"] != null 
            && obj["5"] != null 
            && obj["6"] != null 
            && obj["7"] != null;
    }-*/;

    protected WaveletSnapshot() {}

    // getters and setters

    // waveletId

    public final native String getWaveletId() /*-{
        return this["1"] || "";
    }-*/;

    public final native WaveletSnapshot setWaveletId(String waveletId) /*-{
        this["1"] = waveletId;
        return this;
    }-*/;

    public final native void clearWaveletId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveletId() /*-{
        return this["1"] != null;
    }-*/;

    // participant

    public final native JsArrayString getParticipantArray() /*-{
        return this["2"];
    }-*/;

    public final java.util.List<String> getParticipantList() {
        JsArrayString array = getParticipantArray();
        java.util.List<String> list = new java.util.ArrayList<String>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getParticipantCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native WaveletSnapshot setParticipantArray(JsArrayString participant) /*-{
        this["2"] = participant;
        return this;
    }-*/;

    public final native JsArrayString clearParticipantArray() /*-{
        return (this["2"] = []);
    }-*/;

    public final String getParticipant(int index) {
        JsArrayString array = getParticipantArray();
        return array == null ? null : array.get(index);
    }

    public final int getParticipantCount() {
        JsArrayString array = getParticipantArray();
        return array == null ? 0 : array.length();
    }

    public final void addParticipant(String participant) {
        JsArrayString array = getParticipantArray();
        if(array == null)
            array = clearParticipantArray();
        array.push(participant);
    }

    // document

    public final native JsArray<DocumentSnapshot> getDocumentArray() /*-{
        return this["3"];
    }-*/;

    public final java.util.List<DocumentSnapshot> getDocumentList() {
        JsArray<DocumentSnapshot> array = getDocumentArray();
        java.util.List<DocumentSnapshot> list = new java.util.ArrayList<DocumentSnapshot>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getDocumentCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native WaveletSnapshot setDocumentArray(JsArray<DocumentSnapshot> document) /*-{
        this["3"] = document;
        return this;
    }-*/;

    public final native JsArray<DocumentSnapshot> clearDocumentArray() /*-{
        return (this["3"] = []);
    }-*/;

    public final DocumentSnapshot getDocument(int index) {
        JsArray<DocumentSnapshot> array = getDocumentArray();
        return array == null ? null : array.get(index);
    }

    public final int getDocumentCount() {
        JsArray<DocumentSnapshot> array = getDocumentArray();
        return array == null ? 0 : array.length();
    }

    public final void addDocument(DocumentSnapshot document) {
        JsArray<DocumentSnapshot> array = getDocumentArray();
        if(array == null)
            array = clearDocumentArray();
        array.push(document);
    }

    // version

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getVersion() /*-{
        return this["4"];
    }-*/;

    public final native WaveletSnapshot setVersion(org.waveprotocol.wave.federation.ProtocolHashedVersion version) /*-{
        this["4"] = version;
        return this;
    }-*/;

    public final native void clearVersion() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasVersion() /*-{
        return this["4"] != null;
    }-*/;

    // lastModifiedTime

    public final native double getLastModifiedTime() /*-{
        return this["5"] || 0;
    }-*/;

    public final native WaveletSnapshot setLastModifiedTime(double lastModifiedTime) /*-{
        this["5"] = lastModifiedTime;
        return this;
    }-*/;

    public final native void clearLastModifiedTime() /*-{
        delete this["5"];
    }-*/;

    public final native boolean hasLastModifiedTime() /*-{
        return this["5"] != null;
    }-*/;

    // creator

    public final native String getCreator() /*-{
        return this["6"] || "";
    }-*/;

    public final native WaveletSnapshot setCreator(String creator) /*-{
        this["6"] = creator;
        return this;
    }-*/;

    public final native void clearCreator() /*-{
        delete this["6"];
    }-*/;

    public final native boolean hasCreator() /*-{
        return this["6"] != null;
    }-*/;

    // creationTime

    public final native double getCreationTime() /*-{
        return this["7"] || 0;
    }-*/;

    public final native WaveletSnapshot setCreationTime(double creationTime) /*-{
        this["7"] = creationTime;
        return this;
    }-*/;

    public final native void clearCreationTime() /*-{
        delete this["7"];
    }-*/;

    public final native boolean hasCreationTime() /*-{
        return this["7"] != null;
    }-*/;


}