// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.wave.examples.fedone.waveserver;

import com.google.gwt.core.client.*;

public class DocumentSnapshot extends JavaScriptObject  {


    public static class Builder extends DocumentSnapshot {
      protected Builder() { }
      public final DocumentSnapshot build() {
        return (DocumentSnapshot)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new DocumentSnapshot instance 
     *
     * @return new DocumentSnapshot instance
     */
    public static native DocumentSnapshot create() /*-{
        return {
          "_protoMessageName": "DocumentSnapshot",              
        };
    }-*/;

    /**
     * Creates a new JsArray<DocumentSnapshot> instance 
     *
     * @return new JsArray<DocumentSnapshot> instance
     */
    public static native JsArray<DocumentSnapshot> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a DocumentSnapshot (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return DocumentSnapshot
     */
    public static native DocumentSnapshot get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<DocumentSnapshot> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<DocumentSnapshot> 
     */
    public static native JsArray<DocumentSnapshot> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a DocumentSnapshot from a json string
     *
     * @param json string to be parsed/evaluated
     * @return DocumentSnapshot 
     */
    public static native DocumentSnapshot parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<DocumentSnapshot> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<DocumentSnapshot> 
     */
    public static native JsArray<DocumentSnapshot> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param DocumentSnapshot the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(DocumentSnapshot obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + @org.waveprotocol.wave.federation.ProtocolDocumentOperation::stringify(Lorg/waveprotocol/wave/federation/ProtocolDocumentOperation;)(_2));

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(DocumentSnapshot obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected DocumentSnapshot() {}

    // getters and setters

    // documentId

    public final native String getDocumentId() /*-{
        return this["1"] || "";
    }-*/;

    public final native DocumentSnapshot setDocumentId(String documentId) /*-{
        this["1"] = documentId;
        return this;
    }-*/;

    public final native void clearDocumentId() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasDocumentId() /*-{
        return this["1"] != null;
    }-*/;

    // documentOperation

    public final native org.waveprotocol.wave.federation.ProtocolDocumentOperation getDocumentOperation() /*-{
        return this["2"];
    }-*/;

    public final native DocumentSnapshot setDocumentOperation(org.waveprotocol.wave.federation.ProtocolDocumentOperation documentOperation) /*-{
        this["2"] = documentOperation;
        return this;
    }-*/;

    public final native void clearDocumentOperation() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasDocumentOperation() /*-{
        return this["2"] != null;
    }-*/;


}