// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.wave.examples.fedone.waveserver;

import com.google.gwt.core.client.*;

public class ProtocolWaveletUpdate extends JavaScriptObject  {


    public static class Builder extends ProtocolWaveletUpdate {
      protected Builder() { }
      public final ProtocolWaveletUpdate build() {
        return (ProtocolWaveletUpdate)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolWaveletUpdate instance 
     *
     * @return new ProtocolWaveletUpdate instance
     */
    public static native ProtocolWaveletUpdate create() /*-{
        return {
          "_protoMessageName": "ProtocolWaveletUpdate",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolWaveletUpdate> instance 
     *
     * @return new JsArray<ProtocolWaveletUpdate> instance
     */
    public static native JsArray<ProtocolWaveletUpdate> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolWaveletUpdate (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolWaveletUpdate
     */
    public static native ProtocolWaveletUpdate get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolWaveletUpdate> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolWaveletUpdate> 
     */
    public static native JsArray<ProtocolWaveletUpdate> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolWaveletUpdate from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolWaveletUpdate 
     */
    public static native ProtocolWaveletUpdate parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolWaveletUpdate> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolWaveletUpdate> 
     */
    public static native JsArray<ProtocolWaveletUpdate> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolWaveletUpdate the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolWaveletUpdate obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null && _2.length != 0) {
            var b = [], fn = @org.waveprotocol.wave.federation.ProtocolWaveletDelta::stringify(Lorg/waveprotocol/wave/federation/ProtocolWaveletDelta;);
            for(var i=0,l=_2.length; i<l; i++)
                b.push(fn(_2[i]));
            buf.push("\"2\":[" + b.join(",") + "]");
        }
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_3));
        var _4 = obj["4"];
        if(_4 != null)
            buf.push("\"4\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_4));
        var _5 = obj["5"];
        if(_5 != null)
            buf.push("\"5\":" + @org.waveprotocol.wave.examples.fedone.waveserver.WaveletSnapshot::stringify(Lorg/waveprotocol/wave/examples/fedone/waveserver/WaveletSnapshot;)(_5));
        var _6 = obj["6"];
        if(_6 != null)
            buf.push("\"6\":" + _6);
        var _7 = obj["7"];
        if(_7 != null)
            buf.push("\"7\":\"" + _7 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolWaveletUpdate obj) /*-{
        return 
            obj["1"] != null;
    }-*/;

    protected ProtocolWaveletUpdate() {}

    // getters and setters

    // waveletName

    public final native String getWaveletName() /*-{
        return this["1"] || "";
    }-*/;

    public final native ProtocolWaveletUpdate setWaveletName(String waveletName) /*-{
        this["1"] = waveletName;
        return this;
    }-*/;

    public final native void clearWaveletName() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveletName() /*-{
        return this["1"] != null;
    }-*/;

    // appliedDelta

    public final native JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> getAppliedDeltaArray() /*-{
        return this["2"];
    }-*/;

    public final java.util.List<org.waveprotocol.wave.federation.ProtocolWaveletDelta> getAppliedDeltaList() {
        JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> array = getAppliedDeltaArray();
        java.util.List<org.waveprotocol.wave.federation.ProtocolWaveletDelta> list = new java.util.ArrayList<org.waveprotocol.wave.federation.ProtocolWaveletDelta>();
        
        if (array == null) {
          return null; 
        }
        for (int i=0; i < getAppliedDeltaCount(); i++) {
          list.add(array.get(i));
        }
        return list;
    }

    public final native ProtocolWaveletUpdate setAppliedDeltaArray(JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> appliedDelta) /*-{
        this["2"] = appliedDelta;
        return this;
    }-*/;

    public final native JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> clearAppliedDeltaArray() /*-{
        return (this["2"] = []);
    }-*/;

    public final org.waveprotocol.wave.federation.ProtocolWaveletDelta getAppliedDelta(int index) {
        JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> array = getAppliedDeltaArray();
        return array == null ? null : array.get(index);
    }

    public final int getAppliedDeltaCount() {
        JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> array = getAppliedDeltaArray();
        return array == null ? 0 : array.length();
    }

    public final void addAppliedDelta(org.waveprotocol.wave.federation.ProtocolWaveletDelta appliedDelta) {
        JsArray<org.waveprotocol.wave.federation.ProtocolWaveletDelta> array = getAppliedDeltaArray();
        if(array == null)
            array = clearAppliedDeltaArray();
        array.push(appliedDelta);
    }

    // commitNotice

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getCommitNotice() /*-{
        return this["3"];
    }-*/;

    public final native ProtocolWaveletUpdate setCommitNotice(org.waveprotocol.wave.federation.ProtocolHashedVersion commitNotice) /*-{
        this["3"] = commitNotice;
        return this;
    }-*/;

    public final native void clearCommitNotice() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasCommitNotice() /*-{
        return this["3"] != null;
    }-*/;

    // resultingVersion

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getResultingVersion() /*-{
        return this["4"];
    }-*/;

    public final native ProtocolWaveletUpdate setResultingVersion(org.waveprotocol.wave.federation.ProtocolHashedVersion resultingVersion) /*-{
        this["4"] = resultingVersion;
        return this;
    }-*/;

    public final native void clearResultingVersion() /*-{
        delete this["4"];
    }-*/;

    public final native boolean hasResultingVersion() /*-{
        return this["4"] != null;
    }-*/;

    // snapshot

    public final native WaveletSnapshot getSnapshot() /*-{
        return this["5"];
    }-*/;

    public final native ProtocolWaveletUpdate setSnapshot(WaveletSnapshot snapshot) /*-{
        this["5"] = snapshot;
        return this;
    }-*/;

    public final native void clearSnapshot() /*-{
        delete this["5"];
    }-*/;

    public final native boolean hasSnapshot() /*-{
        return this["5"] != null;
    }-*/;

    // marker

    public final native boolean getMarker() /*-{
        return this["6"] || false;
    }-*/;

    public final native ProtocolWaveletUpdate setMarker(boolean marker) /*-{
        this["6"] = marker;
        return this;
    }-*/;

    public final native void clearMarker() /*-{
        delete this["6"];
    }-*/;

    public final native boolean hasMarker() /*-{
        return this["6"] != null;
    }-*/;

    // channelId

    public final native String getChannelId() /*-{
        return this["7"] || "";
    }-*/;

    public final native ProtocolWaveletUpdate setChannelId(String channelId) /*-{
        this["7"] = channelId;
        return this;
    }-*/;

    public final native void clearChannelId() /*-{
        delete this["7"];
    }-*/;

    public final native boolean hasChannelId() /*-{
        return this["7"] != null;
    }-*/;


}