// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.wave.examples.fedone.waveserver;

import com.google.gwt.core.client.*;

public class ProtocolSubmitRequest extends JavaScriptObject  {


    public static class Builder extends ProtocolSubmitRequest {
      protected Builder() { }
      public final ProtocolSubmitRequest build() {
        return (ProtocolSubmitRequest)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new ProtocolSubmitRequest instance 
     *
     * @return new ProtocolSubmitRequest instance
     */
    public static native ProtocolSubmitRequest create() /*-{
        return {
          "_protoMessageName": "ProtocolSubmitRequest",              
        };
    }-*/;

    /**
     * Creates a new JsArray<ProtocolSubmitRequest> instance 
     *
     * @return new JsArray<ProtocolSubmitRequest> instance
     */
    public static native JsArray<ProtocolSubmitRequest> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a ProtocolSubmitRequest (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return ProtocolSubmitRequest
     */
    public static native ProtocolSubmitRequest get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<ProtocolSubmitRequest> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<ProtocolSubmitRequest> 
     */
    public static native JsArray<ProtocolSubmitRequest> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a ProtocolSubmitRequest from a json string
     *
     * @param json string to be parsed/evaluated
     * @return ProtocolSubmitRequest 
     */
    public static native ProtocolSubmitRequest parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<ProtocolSubmitRequest> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<ProtocolSubmitRequest> 
     */
    public static native JsArray<ProtocolSubmitRequest> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param ProtocolSubmitRequest the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(ProtocolSubmitRequest obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + @org.waveprotocol.wave.federation.ProtocolWaveletDelta::stringify(Lorg/waveprotocol/wave/federation/ProtocolWaveletDelta;)(_2));
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":\"" + _3 + "\"");

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(ProtocolSubmitRequest obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null;
    }-*/;

    protected ProtocolSubmitRequest() {}

    // getters and setters

    // waveletName

    public final native String getWaveletName() /*-{
        return this["1"] || "";
    }-*/;

    public final native ProtocolSubmitRequest setWaveletName(String waveletName) /*-{
        this["1"] = waveletName;
        return this;
    }-*/;

    public final native void clearWaveletName() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveletName() /*-{
        return this["1"] != null;
    }-*/;

    // delta

    public final native org.waveprotocol.wave.federation.ProtocolWaveletDelta getDelta() /*-{
        return this["2"];
    }-*/;

    public final native ProtocolSubmitRequest setDelta(org.waveprotocol.wave.federation.ProtocolWaveletDelta delta) /*-{
        this["2"] = delta;
        return this;
    }-*/;

    public final native void clearDelta() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasDelta() /*-{
        return this["2"] != null;
    }-*/;

    // channelId

    public final native String getChannelId() /*-{
        return this["3"] || "";
    }-*/;

    public final native ProtocolSubmitRequest setChannelId(String channelId) /*-{
        this["3"] = channelId;
        return this;
    }-*/;

    public final native void clearChannelId() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasChannelId() /*-{
        return this["3"] != null;
    }-*/;


}