// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from waveclient-rpc.proto

package org.waveprotocol.wave.examples.fedone.waveserver;

import com.google.gwt.core.client.*;

public class WaveletSnapshotAndVersion extends JavaScriptObject  {


    public static class Builder extends WaveletSnapshotAndVersion {
      protected Builder() { }
      public final WaveletSnapshotAndVersion build() {
        return (WaveletSnapshotAndVersion)this;
      }
      public static native Builder create() /*-{
        return {
        };
      }-*/;
    }

    public static final Builder newBuilder() {
      return Builder.create();
    }
    
    /**
     * Creates a new WaveletSnapshotAndVersion instance 
     *
     * @return new WaveletSnapshotAndVersion instance
     */
    public static native WaveletSnapshotAndVersion create() /*-{
        return {
          "_protoMessageName": "WaveletSnapshotAndVersion",              
        };
    }-*/;

    /**
     * Creates a new JsArray<WaveletSnapshotAndVersion> instance 
     *
     * @return new JsArray<WaveletSnapshotAndVersion> instance
     */
    public static native JsArray<WaveletSnapshotAndVersion> createArray() /*-{
        return [];
    }-*/;

    /**
     * Returns the name of this protocol buffer.
     */
    public static native String getProtocolBufferName(JavaScriptObject instance) /*-{
        return instance._protoMessageName;
    }-*/;

    /**
     * Gets a WaveletSnapshotAndVersion (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return WaveletSnapshotAndVersion
     */
    public static native WaveletSnapshotAndVersion get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Gets a JsArray<WaveletSnapshotAndVersion> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<WaveletSnapshotAndVersion> 
     */
    public static native JsArray<WaveletSnapshotAndVersion> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;

    /**
     * Parses a WaveletSnapshotAndVersion from a json string
     *
     * @param json string to be parsed/evaluated
     * @return WaveletSnapshotAndVersion 
     */
    public static native WaveletSnapshotAndVersion parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;

    /**
     * Parses a JsArray<WaveletSnapshotAndVersion> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<WaveletSnapshotAndVersion> 
     */
    public static native JsArray<WaveletSnapshotAndVersion> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param WaveletSnapshotAndVersion the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(WaveletSnapshotAndVersion obj) /*-{
        var buf = [];
        var _1 = obj["1"];
        if(_1 != null)
            buf.push("\"1\":\"" + _1 + "\"");
        var _2 = obj["2"];
        if(_2 != null)
            buf.push("\"2\":" + @org.waveprotocol.wave.federation.ProtocolHashedVersion::stringify(Lorg/waveprotocol/wave/federation/ProtocolHashedVersion;)(_2));
        var _3 = obj["3"];
        if(_3 != null)
            buf.push("\"3\":" + @org.waveprotocol.wave.examples.fedone.waveserver.WaveletSnapshot::stringify(Lorg/waveprotocol/wave/examples/fedone/waveserver/WaveletSnapshot;)(_3));

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(WaveletSnapshotAndVersion obj) /*-{
        return 
            obj["1"] != null 
            && obj["2"] != null 
            && obj["3"] != null;
    }-*/;

    protected WaveletSnapshotAndVersion() {}

    // getters and setters

    // waveletName

    public final native String getWaveletName() /*-{
        return this["1"] || "";
    }-*/;

    public final native WaveletSnapshotAndVersion setWaveletName(String waveletName) /*-{
        this["1"] = waveletName;
        return this;
    }-*/;

    public final native void clearWaveletName() /*-{
        delete this["1"];
    }-*/;

    public final native boolean hasWaveletName() /*-{
        return this["1"] != null;
    }-*/;

    // version

    public final native org.waveprotocol.wave.federation.ProtocolHashedVersion getVersion() /*-{
        return this["2"];
    }-*/;

    public final native WaveletSnapshotAndVersion setVersion(org.waveprotocol.wave.federation.ProtocolHashedVersion version) /*-{
        this["2"] = version;
        return this;
    }-*/;

    public final native void clearVersion() /*-{
        delete this["2"];
    }-*/;

    public final native boolean hasVersion() /*-{
        return this["2"] != null;
    }-*/;

    // snapshot

    public final native WaveletSnapshot getSnapshot() /*-{
        return this["3"];
    }-*/;

    public final native WaveletSnapshotAndVersion setSnapshot(WaveletSnapshot snapshot) /*-{
        this["3"] = snapshot;
        return this;
    }-*/;

    public final native void clearSnapshot() /*-{
        delete this["3"];
    }-*/;

    public final native boolean hasSnapshot() /*-{
        return this["3"] != null;
    }-*/;


}